// Proverb data for the new tab page.
//
// Proverbs are taken from the Telugu Wikipedia page "సామెతల జాబితా"
// (CC BY-SA 4.0), cleaned up and de-duplicated. Riddles, broken entries and
// crude or demeaning proverbs were left out.
//
// Each entry: { text, meaning, en }
//   text    – the proverb
//   meaning – its sense / when it is used, in Telugu (భావం)
//   en      – a short English gloss

const PROVERBS_SOURCE = {
  name: "te.wikipedia.org – సామెతల జాబితా",
  url: "https://te.wikipedia.org/wiki/%E0%B0%B8%E0%B0%BE%E0%B0%AE%E0%B1%86%E0%B0%A4%E0%B0%B2_%E0%B0%9C%E0%B0%BE%E0%B0%AC%E0%B0%BF%E0%B0%A4%E0%B0%BE",
  license: "CC BY-SA 4.0",
};

const PROVERBS = [
  // అ
  { text: "అంగట్లో అన్నీ ఉన్నా అల్లుడి నోట్లో శని", meaning: "అన్నీ అందుబాటులో ఉన్నా అదృష్టం లేకపోతే ఏదీ దక్కదు.", en: "The market is full, yet nothing reaches the unlucky son-in-law's mouth — plenty around, but no luck to enjoy it." },
  { text: "అంత్య నిష్ఠూరం కన్నా ఆది నిష్ఠూరం మేలు", meaning: "తర్వాత గొడవపడటం కన్నా మొదట్లోనే నిక్కచ్చిగా మాట్లాడుకోవడం మేలు.", en: "Better to be blunt at the start than bitter at the end." },
  { text: "అందని పండ్లకు అర్రులు చాచినట్లు", meaning: "తనకు అందని, దక్కని వాటి కోసం ఆరాటపడటం.", en: "Stretching one's neck for fruit out of reach — craving the unattainable." },
  { text: "అందని ద్రాక్ష పుల్లన", meaning: "దొరకని దాన్ని చెడ్డదని తీసిపారేసి మనసును సమాధానపరచుకోవడం.", en: "Grapes out of reach are sour." },
  { text: "అందరికీ శకునం చెప్పే బల్లి తాను పోయి కుడితిలో పడ్డట్టు", meaning: "ఇతరులకు జాగ్రత్తలు చెప్పేవాడే తన ఆపదను ఊహించలేకపోవడం.", en: "The lizard that foretells omens for everyone fell into the slop tub itself." },
  { text: "అందరూ శ్రీవైష్ణవులే, బుట్టెడు రొయ్యలు మాయమయ్యాయి", meaning: "అందరూ నీతిమంతులమని చెప్పుకుంటారు, కానీ తప్పు మాత్రం జరిగిపోతుంది — కపటత్వాన్ని ఎత్తిచూపే సామెత.", en: "All claim to be strict vegetarians, yet a basket of prawns vanished — hypocrisy." },
  { text: "అందితే జుట్టు, అందకపోతే కాళ్ళు", meaning: "బలం ఉన్నప్పుడు పెత్తనం, లేనప్పుడు కాళ్ళబేరం — అవకాశవాదం.", en: "Grab the hair if you can reach it, else fall at the feet — bully when strong, grovel when weak." },
  { text: "అంబలి తాగేవాడికి మీసాలు ఎత్తేవాడొకడు", meaning: "స్థాయికి మించిన ఆడంబరం, అనవసరమైన హంగులు.", en: "A man drinking thin gruel keeps a servant to lift his moustache — pomp beyond one's means." },
  { text: "అంధుడికి అద్దం చూపించినట్లు", meaning: "ఉపయోగించుకోలేని వారికి ఏదైనా ఇవ్వడం, చెప్పడం వృథా.", en: "Showing a mirror to the blind." },
  { text: "అక్కర ఉన్నంతవరకు ఆదినారాయణ, అక్కర తీరాక గూదనారాయణ", meaning: "అవసరం ఉన్నంతసేపే గౌరవం, అవసరం తీరాక చులకన.", en: "Revered while needed, scorned once the need is met." },
  { text: "అగ్నికి వాయువు తోడైనట్లు", meaning: "ఇప్పటికే ఉన్న సమస్యకు మరొకటి తోడై మరింత పెద్దదవడం.", en: "Wind joining fire — one trouble fuelling another." },
  { text: "అటునుండి నరుక్కు రా", meaning: "నేరుగా కుదరనప్పుడు మరో వైపు నుంచి, మరో దారిలో పని సాధించు.", en: "Cut your way in from the other side — find an indirect route." },
  { text: "అడకత్తెరలో పోకచెక్క", meaning: "రెండు వైపుల నుంచీ ఒత్తిడిలో ఇరుక్కుపోవడం.", en: "A betel nut in the nutcracker — squeezed from both sides." },
  { text: "అడగందే అమ్మైనా అన్నం పెట్టదు", meaning: "అడగకపోతే ఎవరూ ఇవ్వరు; అవసరాన్ని నోరు తెరిచి చెప్పుకోవాలి.", en: "Even a mother won't serve food unless you ask." },
  { text: "అడిగేవాడికి చెప్పేవాడు లోకువ", meaning: "ప్రశ్నించేవాడిదే పైచేయి; జవాబు చెప్పాల్సినవాడు ఎప్పుడూ ఇరకాటంలోనే.", en: "The one who answers is always at the mercy of the one who asks." },
  { text: "అడుసు తొక్కనేల, కాలు కడగనేల", meaning: "తెలిసి తెలిసి బురదలో దిగి తర్వాత బాధపడటమెందుకు — కోరి ఇబ్బంది తెచ్చుకోవద్దు.", en: "Why step in the mud and then wash your feet?" },
  { text: "అడ్డాల నాడు బిడ్డలు గానీ గడ్డాల నాడు కాదు", meaning: "పిల్లలు చిన్నప్పుడే మన మాట వింటారు; పెద్దయ్యాక వారి దారి వారిది.", en: "Children are ours while on the lap, not once they grow beards." },
  { text: "అడిగితే చిరాకు, అడగకపోతే పరాకు", meaning: "ఏం చేసినా తప్పు పట్టే పరిస్థితి.", en: "Ask and they're annoyed; don't ask and you're called careless." },
  { text: "అతని కంటె ఘనుడు ఆచంట మల్లన్న", meaning: "ఒకరిని మించిన ఘనుడు ఇంకొకడు ఉంటాడు (తరచూ వ్యంగ్యంగా).", en: "There's always someone even 'greater' (often said ironically)." },
  { text: "అతి వినయం ధూర్త లక్షణం", meaning: "మితిమీరిన వినయం మోసగాడి లక్షణం; అలాంటివారిని నమ్మొద్దు.", en: "Excessive humility is the mark of a rogue." },
  { text: "అతి రహస్యం బట్టబయలు", meaning: "మరీ దాచిపెట్టాలని చూసే విషయమే త్వరగా బయటపడుతుంది.", en: "The most guarded secret is the first to get out." },
  { text: "అత్త సొమ్ము అల్లుడు దానం చేసినట్లు", meaning: "ఇతరుల సొమ్ముతో దానధర్మాలు చేసి పేరు తెచ్చుకోవడం.", en: "The son-in-law giving away his mother-in-law's money — generosity at others' expense." },
  { text: "అత్తమీద కోపం దుత్తమీద తీర్చుకున్నట్లు", meaning: "ఒకరి మీద కోపాన్ని ఏ సంబంధం లేని మరొకరి మీద చూపడం.", en: "Angry with the mother-in-law, takes it out on the pot." },
  { text: "అత్తా ఒక ఇంటి కోడలే, మామా ఒక ఇంటి అల్లుడే", meaning: "ఈరోజు పెత్తనం చేసేవారూ ఒకప్పుడు అదే స్థితిలో ఉన్నవారే; ఎదుటివారిని అర్థం చేసుకోవాలి.", en: "The mother-in-law was once a daughter-in-law too." },
  { text: "అదిగో పులి అంటే ఇదిగో తోక అన్నట్టు", meaning: "నిజానిజాలు చూడకుండా పుకార్లను ఇంకా పెంచడం.", en: "'There's a tiger!' — 'And here's its tail!' — piling onto a rumour." },
  { text: "అద్దం అబద్ధం ఆడుతుందా", meaning: "నిజం ఎప్పటికీ దాగదు; ఉన్నది ఉన్నట్టు కనిపిస్తుంది.", en: "Does a mirror ever lie?" },
  { text: "అనగా అనగా రాగం, తినగా తినగా రోగం", meaning: "సాధన చేస్తే కళ అబ్బుతుంది; అతిగా తింటే రోగం వస్తుంది.", en: "Keep singing and a melody comes; keep eating and a malady comes." },
  { text: "అనువు గాని చోట అధికుల మనరాదు", meaning: "మనకు అనుకూలం కాని చోట గొప్పలు చెప్పుకోకుండా ఒదిగి ఉండాలి (వేమన).", en: "Where the ground isn't yours, don't claim to be superior." },
  { text: "అనుమానం పెనుభూతం", meaning: "అనుమానం పెద్ద దెయ్యంలా పెరిగి మనసునూ బంధాలనూ పాడుచేస్తుంది.", en: "Suspicion is a giant ghost." },
  { text: "అన్నం పెట్టేవాడికన్నా సున్నం పెట్టేవాళ్ళే ఎక్కువ", meaning: "సాయం చేసేవాళ్ళ కంటే నష్టం చేసేవాళ్ళే ఎక్కువ.", en: "Those who harm you outnumber those who feed you." },
  { text: "అన్నీ ఉన్న ఆకు అణిగిమణిగి ఉంటుంది, ఏమీ లేని ఆకు ఎగిరెగిరి పడుతుంది", meaning: "నిజంగా విషయం ఉన్నవాళ్ళు వినయంగా ఉంటారు; ఏమీ లేనివాళ్ళే ఆర్భాటం చేస్తారు.", en: "A full leaf-plate lies still; an empty one flutters about." },
  { text: "అప్పిచ్చి చూడు, ఆడపిల్లనిచ్చి చూడు", meaning: "అప్పు ఇచ్చినప్పుడు, పిల్లనిచ్చినప్పుడే మనిషి అసలు స్వభావం బయటపడుతుంది.", en: "Lend money or give your daughter in marriage — then you'll know a person." },
  { text: "అప్పు నిప్పులాంటిది", meaning: "అప్పు నిప్పులా కాల్చేస్తుంది; జాగ్రత్తగా ఉండాలి.", en: "Debt is like fire." },
  { text: "అప్పు చేసి పప్పు కూడు", meaning: "అప్పు చేసి మరీ విలాసంగా బతకడం.", en: "Borrowing money to feast." },
  { text: "అప్పులేని వాడే అధిక సంపన్నుడు", meaning: "అప్పు లేకపోవడమే నిజమైన సంపద.", en: "The man without debt is the richest." },
  { text: "అబద్ధం ఆడినా అతికినట్లుండాలి", meaning: "అబద్ధం చెప్పినా నమ్మేలా, పొంతన కుదిరేలా ఉండాలి.", en: "Even a lie should fit." },
  { text: "అభ్యాసం కూసు విద్య", meaning: "సాధన చేస్తే ఏ విద్యైనా వస్తుంది.", en: "Practice makes any skill come easily." },
  { text: "అమ్మ పుట్టిల్లు మేనమామకు తెలియదా", meaning: "అన్నీ తెలిసినవాడి దగ్గర గొప్పలు చెప్పడం, దాచడం వృథా.", en: "Doesn't the uncle know his own sister's birthplace?" },
  { text: "అమ్మ పెట్టా పెట్టదు, అడుక్కు తిననూ తిననివ్వదు", meaning: "తాను సాయం చేయడు, ఇతరుల సాయమూ పొందనివ్వడు.", en: "She won't feed you herself, nor let you beg." },
  { text: "అమ్మకు కూడు పెట్టనివాడు పెద్దమ్మకు కోక పెడతానన్నాడట", meaning: "సొంతవారిని పట్టించుకోకుండా బయటివారికి గొప్ప వాగ్దానాలు చేయడం.", en: "Won't feed his mother, yet promises his aunt a sari." },
  { text: "అమ్మబోతే అడవి, కొనబోతే కొరివి", meaning: "అమ్మాలంటే ధర రాదు, కొనాలంటే చేయి కాలేంత ఖరీదు.", en: "Sell it and it's worth nothing; buy it and it burns your hand." },
  { text: "అయినవాళ్ళకు ఆకుల్లో, కానివాళ్ళకు కంచాల్లో", meaning: "సొంతవారిని నిర్లక్ష్యం చేసి బయటివారికి మర్యాదలు చేయడం.", en: "Leaf plates for family, fine dishes for strangers." },
  { text: "అయిపోయిన పెళ్ళికి మేళాలెందుకు", meaning: "సమయం దాటిపోయాక చేసే పని వృథా.", en: "Why the band after the wedding is over?" },
  { text: "అరఘడియ భోగం, ఆర్నెల్ల రోగం", meaning: "కాసేపటి సుఖం దీర్ఘకాలపు కష్టాన్ని తెస్తుంది.", en: "A moment's pleasure, six months' illness." },
  { text: "అరచేతిలో వైకుంఠం చూపినట్లు", meaning: "జరగని ఆశలు చూపించి మభ్యపెట్టడం.", en: "Showing heaven in the palm of the hand — empty promises." },
  { text: "అరకాసు పనికి ముప్పాతిక బాడుగ", meaning: "పని విలువ కన్నా దానికయ్యే ఖర్చు ఎక్కువ.", en: "Half a coin's job, three-quarters in hire charges." },
  { text: "అరచేతిలో వెన్న పెట్టుకుని నెయ్యి కోసం ఊరంతా తిరిగినట్లు", meaning: "దగ్గరే ఉన్నదాన్ని గుర్తించక బయట వెతకడం.", en: "Butter in hand, searching the whole town for ghee." },
  { text: "అరిచే కుక్క కరవదు", meaning: "ఎక్కువగా బెదిరించేవాళ్ళు నిజంగా హాని చేయరు.", en: "A barking dog seldom bites." },
  { text: "అరటిపండు ఒలిచి చేతిలో పెట్టినట్లు", meaning: "ఏ కష్టం లేకుండా సులభంగా అర్థమయ్యేలా చెప్పడం.", en: "Like a peeled banana placed in the hand — made very easy." },
  { text: "అర్ధరాత్రి మద్దెల దరువు", meaning: "సమయం సందర్భం లేని పని.", en: "Drumming at midnight — badly timed." },
  { text: "అల్లుడికి ఐశ్వర్యం వస్తే అర్ధరాత్రి గొడుగు పట్టమన్నాడట", meaning: "కొత్తగా వచ్చిన సంపదతో వెర్రి ఆడంబరాలు.", en: "The newly rich son-in-law wants an umbrella held over him at midnight." },
  { text: "అల్లం అంటే నాకు తెలీదా, బెల్లంలా పుల్లగా ఉంటుందన్నాడట", meaning: "తెలియని విషయం తెలుసని బుకాయించడం.", en: "'Of course I know ginger — it's sour, like jaggery!'" },
  { text: "అసలే కోతి, ఆపై కల్లు తాగినట్టు", meaning: "స్వతహాగా చంచలమైనవారికి మరో కారణం తోడై మరింత విచ్చలవిడితనం.", en: "A monkey to begin with, and drunk on top of it." },
  { text: "అసలే లేదంటే పెసరపప్పు వండవే పెళ్ళామా అన్నాడట", meaning: "ఏమీ లేని స్థితిలో కూడా గొంతెమ్మ కోరికలు కోరడం.", en: "'There's nothing at home.' — 'Then cook some green-gram dal!'" },
  { text: "అడుక్కునేవాడింటికి బుడబుక్కలవాడు వచ్చినట్టు", meaning: "తానే లేనివాడి దగ్గరకు మరొకరు సాయం అడగడానికి రావడం.", en: "A beggar coming to beg at a beggar's door." },
  { text: "అలిగే బిడ్డతో, చెలిగే గొడ్డుతో వేగడం కష్టం", meaning: "మాటిమాటికీ అలిగేవారితో, బెదిరిపోయేవారితో వ్యవహరించడం కష్టం.", en: "A sulking child and a skittish cow are hard to manage." },
  { text: "అంచు డాబే గానీ పంచె డాబు లేదు", meaning: "పైపై హంగులే తప్ప అసలు విషయం లేదు.", en: "A showy border, but no substance to the cloth." },
  { text: "అంత పెద్ద పుస్తకం చంకలో ఉంటే పంచాంగం చెప్పలేవా అన్నట్లు", meaning: "పైపై చిహ్నాలు చూసి జ్ఞానం ఉందనుకోవడం.", en: "'You carry such a big book — can't you read the almanac?' — judging knowledge by appearances." },
  { text: "అంత ఉరుము ఉరిమి ఇంతేనా కురిసింది", meaning: "హడావుడి ఎక్కువ, ఫలితం తక్కువ.", en: "So much thunder, and only this much rain?" },
  { text: "అంతా మన మంచికే", meaning: "ఏం జరిగినా మన మంచికే అని సానుకూలంగా తీసుకోవడం.", en: "Everything happens for our good." },
  { text: "అందం కోసం పెట్టిన సొమ్ము ఆపదలో అక్కరకు వచ్చిందన్నట్లు", meaning: "అలంకారం కోసం కొన్న నగలే కష్టకాలంలో ఆదుకుంటాయి.", en: "Jewellery bought for beauty comes to the rescue in hard times." },
  { text: "అందరి కాళ్ళకు మొక్కినా అత్తారింటికి పోక తప్పదు", meaning: "తప్పనిసరి దాన్ని ఎంత తప్పించుకోవాలనుకున్నా కుదరదు.", en: "Bow to everyone you like — you'll still have to go to your in-laws' house." },
  { text: "ఆ తాను ముక్కే", meaning: "అందరూ ఒకే రకం, ఒకే మూలం నుంచి వచ్చినవాళ్ళు.", en: "Cut from the same cloth." },

  // ఆ
  { text: "ఆకలి రుచెరుగదు, నిద్ర సుఖమెరుగదు, వలపు సిగ్గెరుగదు", meaning: "ఆకలిగా ఉన్నవాడు రుచి చూడడు, నిద్రవచ్చినవాడు పరుపు చూడడు, ప్రేమలో ఉన్నవాడు సిగ్గుపడడు.", en: "Hunger knows no taste, sleep no comfort, love no shame." },
  { text: "ఆకలేస్తే రోకలి మింగమన్నాడట", meaning: "సమస్యకు పనికిరాని, హాస్యాస్పదమైన పరిష్కారం చెప్పడం.", en: "'Hungry? Swallow a pestle!' — useless advice." },
  { text: "ఆకలని రెండు చేతులతో తింటామా", meaning: "ఎంత అవసరమైనా హద్దులు, మర్యాద దాటకూడదు.", en: "Hungry or not, do we eat with both hands?" },
  { text: "ఆకు వెళ్ళి ముల్లు మీద పడ్డా, ముల్లు వెళ్ళి ఆకు మీద పడ్డా ఆకుకే నష్టం", meaning: "బలవంతుడితో గొడవలో ఎలా జరిగినా బలహీనుడే నష్టపోతాడు.", en: "Whether the leaf falls on the thorn or the thorn on the leaf, it's the leaf that tears." },
  { text: "ఆడబోయిన తీర్థం ఎదురైనట్లు", meaning: "వెతకబోయినదే అనుకోకుండా ఎదురుపడటం — అనుకోని అదృష్టం.", en: "The holy water you set out to bathe in came to meet you." },
  { text: "ఆడలేక మద్దెల ఓడు అన్నట్లు", meaning: "తన చేతకానితనానికి సాధనాలనో ఇతరులనో నిందించడం.", en: "Can't dance, so blames the drum." },
  { text: "ఆత్రగాడికి బుద్ధి మట్టు", meaning: "తొందరపడేవాడికి ఆలోచన తక్కువ.", en: "The hasty have little sense." },
  { text: "ఆత్రపు పెళ్ళికొడుకు అత్త మెళ్ళో తాళి కట్టినట్లు", meaning: "మితిమీరిన తొందరలో నవ్వులపాలయ్యే తప్పులు చేయడం.", en: "The over-eager groom tied the wedding knot around his mother-in-law's neck." },
  { text: "ఆదిలోనే హంసపాదు", meaning: "పని మొదలుపెట్టగానే ఆటంకం.", en: "A stumble at the very first step." },
  { text: "ఆపదలో మొక్కులు, సంపదలో మరపులు", meaning: "కష్టంలో దేవుణ్ణి, సాయం చేసినవారిని తలచుకోవడం; సుఖం రాగానే మరచిపోవడం.", en: "Vows in danger, forgotten in prosperity." },
  { text: "ఆరిపోయే దీపానికి వెలుగెక్కువ", meaning: "అంతానికి ముందు ఒక్కసారిగా వెలిగిపోవడం.", en: "A lamp flares brightest just before it goes out." },
  { text: "ఆరు నెలలు సావాసం చేస్తే వారు వీరవుతారు", meaning: "సహవాసం వల్ల అలవాట్లు, స్వభావం మారిపోతాయి.", en: "Six months together and they become alike." },
  { text: "ఆరోగ్యమే మహాభాగ్యం", meaning: "ఆరోగ్యాన్ని మించిన సంపద లేదు.", en: "Health is the greatest wealth." },
  { text: "ఆలస్యం అమృతం విషం", meaning: "ఆలస్యం చేస్తే అమృతం లాంటి అవకాశం కూడా విషమవుతుంది.", en: "Delay turns nectar into poison." },
  { text: "ఆలి బెల్లమాయె, తల్లి అల్లమాయె", meaning: "పెళ్ళయ్యాక భార్య తీపి, తల్లి చేదు అయిపోవడం.", en: "The wife became jaggery, the mother became ginger." },
  { text: "ఆలూ లేదు చూలూ లేదు, కొడుకు పేరు సోమలింగం", meaning: "జరగని దాని గురించి ముందే ప్రణాళికలు వేయడం.", en: "No wife, no pregnancy — but the son is already named Somalingam." },
  { text: "ఆవు చేలో మేస్తే దూడ గట్టున మేస్తుందా", meaning: "పెద్దలు తప్పు చేస్తే పిల్లలూ అదే దారిలో నడుస్తారు.", en: "If the cow grazes in the field, will the calf stay on the bund?" },
  { text: "ఆవుకు దూడకు లేని బాధ గుంజకెందుకు", meaning: "సంబంధించిన వాళ్ళకు లేని బాధ సంబంధం లేనివారికెందుకు — అనవసర జోక్యం.", en: "The cow and calf don't mind — why does the tethering post?" },
  { text: "ఆవులింతకు అన్న ఉన్నాడు కానీ తుమ్ముకు తమ్ముడు లేడు", meaning: "ఆవలింత ఒకరి నుంచి ఒకరికి అంటుకుంటుంది, తుమ్ము అలా కాదు.", en: "A yawn has an elder brother, but a sneeze has no younger one — yawns are catching, sneezes aren't." },
  { text: "ఆవులిస్తే పేగులు లెక్కపెట్టే రకం", meaning: "చిన్న సూచనతోనే ఎదుటివారి మనసులోది గ్రహించే చురుకైనవాడు.", en: "Counts your intestines when you yawn — extremely perceptive." },
  { text: "ఆశపడి ఆరు లంఖణాలు చేస్తే ఆ వేళా జొన్నకూడే గతి అయినట్టు", meaning: "గొప్పదాని కోసం కష్టపడినా చివరకు మామూలుదే దక్కడం.", en: "Fasted six days hoping for a feast, and still ended up with plain millet." },
  { text: "ఆవులు పోట్లాడుకుని లేగల కాళ్ళు విరగదొక్కినట్లు", meaning: "పెద్దల గొడవల్లో చిన్నవాళ్ళు నలిగిపోవడం.", en: "When the cows fight, the calves' legs get broken." },

  // ఇ
  { text: "ఇంట్లో పిల్లి, వీధిలో పులి", meaning: "ఇంట్లో నోరు మెదపడు, బయట మాత్రం పెద్ద వీరుడు.", en: "A cat at home, a tiger in the street." },
  { text: "ఇంట్లో రామయ్య, వీధిలో కృష్ణయ్య", meaning: "ఇంట్లో బుద్ధిమంతుడిలా, బయట చిలిపిగా ఉండటం — రెండు ముఖాలు.", en: "A Rama at home, a Krishna in the street — two faces." },
  { text: "ఇంత బతుకూ బతికి ఇంటెనకాల చచ్చినట్టు", meaning: "గొప్పగా బతికి చివరకు అవమానకరంగా ముగియడం.", en: "Lived so grandly, only to die behind the house." },
  { text: "ఇల్లలకగానే పండగ కాదు", meaning: "ఏర్పాట్లు మొదలుపెట్టినంత మాత్రాన పని పూర్తయినట్టు కాదు.", en: "Plastering the floor doesn't make it a festival." },
  { text: "ఇల్లలుకుతూ పేరు మరిచిపోయినట్లు", meaning: "పనిలో మునిగిపోయి అసలు విషయం మరిచిపోవడం.", en: "So busy plastering the house, she forgot her own name." },
  { text: "ఇల్లు కాలి ఒకడేడుస్తుంటే చుట్టకు నిప్పు అడిగాడట ఒకడు", meaning: "ఇతరుల కష్టంలో కూడా స్వార్థం చూసుకోవడం.", en: "One man weeps over his burning house; another asks for a light for his cigar." },
  { text: "ఇల్లు ఇరకాటం, ఆలి మర్కటం", meaning: "ఇల్లు ఇరుకు, ఇల్లాలు చిర్రుబుర్రు — అన్ని వైపులా ఇబ్బంది.", en: "A cramped house and a cranky spouse — trouble on every side." },
  { text: "ఇల్లు పీకి పందిరి వేసినట్లు", meaning: "ఉన్నదాన్ని పాడుచేసి తాత్కాలిక ఆర్భాటం చేయడం.", en: "Tearing down the house to build a wedding canopy." },
  { text: "ఇసుక తక్కెడ, పేడ తక్కెడ", meaning: "ఇద్దరూ మోసగాళ్ళే; ఒకరికొకరు తగినవాళ్ళు.", en: "One pays in sand, the other in dung — two cheats deserving each other." },
  { text: "ఇల్లు ఇచ్చినవాడికి, మజ్జిగ పోసినవాడికి మంచిలేదు", meaning: "సాయం చేసినవారికే చివరకు చెడ్డపేరు వస్తుంది.", en: "Whoever lends a house or gives buttermilk gets no thanks." },
  { text: "ఇంట గెలిచి రచ్చ గెలువు", meaning: "ముందు ఇంట్లో వాళ్ళ మెప్పు పొంది, ఆ తర్వాత బయట గెలవాలి.", en: "Win at home first, then win the world." },
  { text: "ఇల్లు కట్టి చూడు, పెళ్ళి చేసి చూడు", meaning: "ఇల్లు కట్టడం, పెళ్ళి చేయడం ఎంత కష్టమో చేసినవారికే తెలుస్తుంది.", en: "Build a house or arrange a wedding — then you'll know how hard it is." },
  { text: "ఇంటి దొంగను ఈశ్వరుడైనా పట్టలేడు", meaning: "ఇంట్లోవాళ్ళే మోసం చేస్తే కనిపెట్టడం దేవుడికైనా కష్టం.", en: "Not even God can catch a thief within the house." },

  // ఉ, ఊ
  { text: "ఉన్నమాటంటే ఉలుకెక్కువ", meaning: "నిజం చెబితే ఎదుటివారికి కోపం వస్తుంది.", en: "Speak the truth and people flinch." },
  { text: "ఉన్నదీ పోయె, ఉంచుకున్నదీ పోయె", meaning: "అత్యాశతో ఉన్నదాన్ని కూడా పోగొట్టుకోవడం.", en: "Lost what I had, and what I'd saved too." },
  { text: "ఉయ్యాలలో పిల్లను పెట్టుకుని ఊరంతా వెతికినట్టు", meaning: "దగ్గరే ఉన్నదాన్ని గమనించక ఎక్కడెక్కడో వెతకడం.", en: "Searching the whole village for the baby that's in the cradle." },
  { text: "ఉరుము ఉరిమి మంగలం మీద పడినట్లు", meaning: "ఎక్కడో పుట్టిన కోపం ఏ సంబంధం లేనివారి మీద పడటం.", en: "The thunder roared and struck the frying pan." },
  { text: "ఉల్లి చేసే మేలు తల్లి కూడా చేయదు", meaning: "ఉల్లిపాయ ఆరోగ్యానికి అంత మేలు చేస్తుంది.", en: "An onion does you more good than even a mother." },
  { text: "ఉపాయం లేనివాడిని ఊళ్ళోంచి వెళ్ళగొట్టమన్నారు", meaning: "సమయస్ఫూర్తి, ఉపాయం లేనివాడు ఎక్కడా నెగ్గలేడు.", en: "A man without resourcefulness may as well be driven out of the village." },
  { text: "ఉట్టికెగరలేనమ్మ స్వర్గానికి ఎగిరినట్లు", meaning: "చిన్న పని చేతకానివాడు పెద్ద పనులు చేస్తానని గొప్పలు చెప్పడం.", en: "Can't jump up to the hanging pot, yet claims to fly to heaven." },
  { text: "ఊపిరి ఉంటే ఉప్పు అమ్ముకొని బతకొచ్చు", meaning: "ప్రాణం ఉంటే ఏదో విధంగా బతకవచ్చు; ముందు ప్రాణం కాపాడుకో.", en: "If you're alive, you can live even by selling salt." },
  { text: "ఊరంతా ఒకదారి, ఉలిపికట్టెదొక దారి", meaning: "అందరూ ఒకలా ఉంటే, ఒక్కడు మాత్రం మొండిగా వేరే దారిలో వెళ్ళడం.", en: "The whole village goes one way; the odd one goes another." },
  { text: "ఊరు పొమ్మంటోంది, కాడు రమ్మంటోంది", meaning: "వృద్ధాప్యం వచ్చి చివరి రోజులు దగ్గరపడటం.", en: "The village says go, the cremation ground says come — old age." },
  { text: "ఊరుకున్నంత ఉత్తమం లేదు, బోడిగుండంత సుఖం లేదు", meaning: "అనవసరంగా మాట్లాడకుండా ఊరుకోవడమే ఉత్తమం.", en: "Nothing better than keeping quiet, nothing easier than a shaven head." },
  { text: "ఊళ్ళో పెళ్ళికి కుక్కల హడావుడి", meaning: "సంబంధం లేనివాళ్ళే ఎక్కువ హడావుడి చేయడం.", en: "A wedding in the village, and the dogs make the most fuss." },
  { text: "ఊరుకున్న శంఖాన్ని ఊది చెడగొట్టినట్లు", meaning: "బాగున్నదాన్ని అనవసరంగా కదిలించి పాడుచేయడం.", en: "Blowing a quiet conch until it cracks — ruining what was fine." },
  { text: "ఊరికి ఉపకారి, ఆలికి అపకారి", meaning: "బయటివారందరికీ సాయం, ఇంట్లోవాళ్ళకు మాత్రం నిర్లక్ష్యం.", en: "A help to the whole village, a harm to his own wife." },
  { text: "ఊరక రారు మహానుభావులు", meaning: "గొప్పవాళ్ళు ఏదో పని లేనిదే రారు.", en: "Great people never visit without a purpose." },

  // ఎ, ఏ
  { text: "ఎంకి పెళ్ళి సుబ్బి చావుకొచ్చింది", meaning: "ఒకరి పని మరొకరికి ఆపద తెచ్చిపెట్టడం.", en: "Yenki's wedding became Subbi's death — one's joy, another's ruin." },
  { text: "ఎంగిలి చేత్తో కాకిని తోలనివాడు", meaning: "పరమ పిసినారి — ఎంగిలి చేయి విదిలిస్తే కాకికి మెతుకు పడుతుందని కూడా తోలడు.", en: "Won't even shoo a crow with a food-smeared hand — a miser." },
  { text: "ఎంత చెట్టుకు అంత గాలి", meaning: "ఎంత స్థాయి ఉంటే అంత స్థాయి సమస్యలు.", en: "The bigger the tree, the stronger the wind it faces." },
  { text: "ఎక్కడ వేసిన గొంగళి అక్కడే", meaning: "ఏ మార్పూ లేదు, పురోగతీ లేదు.", en: "The blanket lies right where it was dropped — no progress at all." },
  { text: "ఎక్కడైనా బావ గానీ వంగతోట దగ్గర కాదు", meaning: "బంధుత్వం ఒకటి, లాభనష్టాల విషయం మరొకటి.", en: "He's my brother-in-law anywhere — except in my brinjal garden." },
  { text: "ఎడ్డెమంటే తెడ్డెమనే రకం", meaning: "ఏం చెప్పినా దానికి వ్యతిరేకంగా మాట్లాడేవాడు.", en: "Say one thing and he says the opposite." },
  { text: "ఎద్దు ఈనిందంటే దూడను గాట కట్టేయమన్నాడట", meaning: "ఆలోచించకుండా అసంభవమైన మాటను నమ్మేయడం.", en: "Told 'the ox has calved', he said 'tie the calf up then'." },
  { text: "ఎద్దు పుండు కాకికి ముద్దు", meaning: "ఒకరి బాధ మరొకరికి లాభం, ఆనందం.", en: "The ox's sore is the crow's delight." },
  { text: "ఎద్దుగా ఏడాది బతకడం కంటే ఆంబోతుగా ఆర్నెల్లు బతకడం మేలు", meaning: "బానిసలా ఎక్కువకాలం బతకడం కన్నా స్వేచ్ఛగా కొద్దికాలం బతకడం మేలు.", en: "Better six months as a free bull than a year as a yoked ox." },
  { text: "ఎలుక తోక తెచ్చి ఎన్నినాళ్ళు ఉతికినా నలుపు నలుపే", meaning: "పుట్టుకతో వచ్చిన స్వభావం ఎంత ప్రయత్నించినా మారదు.", en: "Wash a rat's tail as long as you like — black stays black." },
  { text: "ఎలుకలున్నాయని ఇల్లు తగలబెట్టినట్లు", meaning: "చిన్న సమస్య కోసం పెద్ద నష్టం చేసుకోవడం.", en: "Burning down the house to get rid of the rats." },
  { text: "ఎరువు సొమ్ము బరువు చేటు", meaning: "అరువు తెచ్చుకున్న సొమ్ము భారమే, నష్టమే.", en: "Borrowed finery is a burden and a risk." },
  { text: "ఏకులా వచ్చి మేకులా తగులుకున్నట్టు", meaning: "చిన్నగా వచ్చి చేరి, తర్వాత వదలకుండా పాతుకుపోవడం.", en: "Came in soft as cotton, stuck fast like a nail." },
  { text: "ఏ ఎండకా గొడుగు", meaning: "పరిస్థితిని బట్టి మాట, తీరు మార్చుకోవడం — అవకాశవాదం.", en: "A different umbrella for every sun — changing sides with the weather." },
  { text: "ఏ చెట్టూ లేని చోట ఆముదం చెట్టే మహావృక్షం", meaning: "గొప్పవాళ్ళు లేని చోట సామాన్యుడే గొప్పవాడిగా చెలామణి అవుతాడు.", en: "Where there are no trees, the castor plant is a mighty tree." },
  { text: "ఏనుగు చచ్చినా బతికినా వెయ్యే", meaning: "గొప్పదాని విలువ ఏ స్థితిలోనూ తగ్గదు.", en: "Dead or alive, an elephant is worth a thousand." },
  { text: "ఏనుగు నెత్తిమీద ఏనుగే మన్ను పోసుకున్నట్లు", meaning: "తన నష్టాన్ని తానే తెచ్చుకోవడం.", en: "The elephant throws dirt on its own head." },
  { text: "ఏనుగులు పడితే ఏనుగులే లేపాలి", meaning: "పెద్దవారి సమస్యలు పెద్దవారే తీర్చగలరు.", en: "When an elephant falls, only elephants can lift it." },
  { text: "ఏరు ఏడామడ ఉండగానే చీర విప్పి చంకన పెట్టుకుందట", meaning: "అవసరం రాకముందే తొందరపాటు.", en: "The river still miles away, she already hitched up her sari." },
  { text: "ఏరు దాటాక తెప్ప తగలేసినట్లు", meaning: "అవసరం తీరాక సాయపడిన దాన్ని, వారిని మరచిపోవడం — కృతఘ్నత.", en: "Burning the raft once the river is crossed." },
  { text: "ఏరు దాటే దాకా ఓడమల్లయ్య, ఏరు దాటాక బోడిమల్లయ్య", meaning: "అవసరం ఉన్నంతసేపు గౌరవం, తీరాక చులకన.", en: "'Boatman Mallayya' till the river is crossed, 'bald Mallayya' after." },

  // ఒ, ఓ
  { text: "ఒడ్డున ఉండి ఎన్నయినా చెప్తారు", meaning: "కష్టం పడనివాళ్ళు సలహాలు తేలిగ్గా చెబుతారు; అనుభవించేవారికే తెలుస్తుంది.", en: "It's easy to give advice from the riverbank." },
  { text: "ఒక దెబ్బకు రెండు పిట్టలు", meaning: "ఒకే ప్రయత్నంతో రెండు పనులు సాధించడం.", en: "Two birds with one stone." },
  { text: "ఒల్లని భార్య చేయి తగిలినా ముప్పే, కాలు తగిలినా తప్పే", meaning: "మనల్ని ఇష్టపడనివారికి మనం ఏం చేసినా తప్పుగానే కనిపిస్తుంది.", en: "To one who dislikes you, a touch of the hand is an offence and a touch of the foot a crime." },
  { text: "ఒక ఒరలో రెండు కత్తులు ఇమడవు", meaning: "ఒకే చోట ఇద్దరు సమాన అధికారులు కలిసి ఉండలేరు.", en: "Two swords don't fit in one sheath." },
  { text: "ఓడలు బళ్ళవుతాయి, బళ్ళు ఓడలవుతాయి", meaning: "కాలం మారుతుంది; ధనికులు పేదలు, పేదలు ధనికులు కావచ్చు.", en: "Ships become carts and carts become ships — fortunes turn." },
  { text: "ఓర్చినమ్మకు తేట నీరు", meaning: "ఓపిక పట్టినవారికి మంచి ఫలితం దక్కుతుంది.", en: "The one who waits gets the clear water." },
  { text: "ఓరిస్తే ఓరుగల్లే పట్టణమవుతుంది", meaning: "ఓర్పుతో ఎంత పెద్ద పనైనా సాధ్యమవుతుంది.", en: "With patience, even Orugallu grows into a city." },

  // క
  { text: "కంచే చేను మేసినట్లు", meaning: "కాపాడాల్సినవాడే దోచుకోవడం.", en: "The fence itself eating the crop — the protector turned thief." },
  { text: "కంచిలో చేయబోయే దొంగతనానికి కాళహస్తి నుంచే వంగి నడిచినట్లు", meaning: "సమయం రాకముందే అతిగా హడావుడి, అతి జాగ్రత్త.", en: "Crouching all the way from Kalahasti for a theft planned in Kanchi." },
  { text: "కంచు మోగునట్లు కనకంబు మోగునా", meaning: "విలువలేనివే ఎక్కువ శబ్దం చేస్తాయి; గొప్పవాళ్ళు ఆర్భాటం చేయరు (వేమన).", en: "Does gold ring as loudly as bronze?" },
  { text: "కంచె లేని చేను, తల్లి లేని బిడ్డ ఒక్కటే", meaning: "రక్షణ లేనివి ఎవరి చేతిలోనైనా నష్టపోతాయి.", en: "A field without a fence and a child without a mother are alike." },
  { text: "కంటికి రెప్ప, కాలికి చెప్పు", meaning: "ఎప్పుడూ వెన్నంటి కాపాడేవి.", en: "The eyelid to the eye, the sandal to the foot — constant protectors." },
  { text: "కందకు లేని దురద కత్తిపీటకెందుకు", meaning: "సంబంధించినవారికి లేని బాధ సంబంధం లేనివారికెందుకు.", en: "If the yam doesn't itch, why should the knife?" },
  { text: "కక్కొచ్చినా కళ్యాణమొచ్చినా ఆగవు", meaning: "కొన్ని విషయాలు వచ్చినప్పుడు ఆపడం ఎవరి తరమూ కాదు.", en: "Neither vomit nor a wedding can be held back once it comes." },
  { text: "కడివెడు గుమ్మడికాయైనా కత్తిపీటకు లోకువే", meaning: "ఎంత పెద్దవాడైనా అధికారం ఉన్నవాడి ముందు తలవంచాల్సిందే.", en: "However big the pumpkin, it bows to the cutting knife." },
  { text: "కడుపుతో ఉన్నామె కనక మానుతుందా", meaning: "జరగాల్సింది జరగక తప్పదు.", en: "Can a pregnant woman avoid giving birth?" },
  { text: "కడుపు చించుకుంటే కాళ్ళ మీద పడుతుంది", meaning: "సొంతవాళ్ళ గుట్టు బయటపెడితే ఆ నష్టం మనకే.", en: "Slit your own belly and it falls on your own feet." },
  { text: "కన్ను పోయేంత కాటుక పెట్టుకోకూడదు", meaning: "మంచిదైనా మితిమీరితే హానే.", en: "Don't apply so much kohl that you lose the eye." },
  { text: "కరవమంటే కప్పకు కోపం, విడవమంటే పాముకు కోపం", meaning: "ఇద్దరి మధ్య ఇరుక్కుని ఎవరి వైపూ మాట్లాడలేని స్థితి.", en: "Say 'bite' and the frog is angry; say 'let go' and the snake is." },
  { text: "కర్ర ఇచ్చి మరీ పళ్ళు రాలగొట్టించుకున్నట్లు", meaning: "తన నష్టానికి తానే సాధనం అందించడం.", en: "Handing over the stick and getting your teeth knocked out." },
  { text: "కర్రలేని వాడిని గొర్రె కూడా కరుస్తుంది", meaning: "బలం, ఆసరా లేనివాడిని అందరూ చులకన చేస్తారు.", en: "Even a sheep bites the man without a stick." },
  { text: "కలిసి ఉంటే కలదు సుఖం", meaning: "ఐకమత్యంతోనే సుఖం, బలం.", en: "Together there is happiness." },
  { text: "కలకాలపు దొంగైనా ఏదో ఒకనాడు దొరుకుతాడు", meaning: "తప్పు ఎంతకాలం దాచినా ఒకరోజు బయటపడుతుంది.", en: "Even a lifelong thief gets caught one day." },
  { text: "కలిసొచ్చే కాలం వస్తే నడిచొచ్చే కొడుకు పుడతాడు", meaning: "అదృష్టం కలిసొస్తే అన్నీ అనుకూలంగా జరుగుతాయి.", en: "When luck turns your way, even a son is born walking." },
  { text: "కలిమి లేములు కావడి కుండలు", meaning: "సంపద, పేదరికం కావడిలోని కుండల్లా పైకీ కిందకీ మారుతుంటాయి.", en: "Wealth and want are like the two pots of a shoulder-pole, rising and falling in turn." },
  { text: "కళ్ళు కావాలంటాయి, కడుపు వద్దంటుంది", meaning: "కడుపు నిండినా కళ్ళ ఆశ తీరదు.", en: "The eyes want more, the stomach says no." },
  { text: "కళ్ళు పోయాక సూర్యనమస్కారాలు", meaning: "నష్టం జరిగిపోయాక జాగ్రత్తలు తీసుకోవడం.", en: "Saluting the sun after losing one's eyes." },
  { text: "కల్ల పసిడికి కాంతి మెండు", meaning: "నకిలీ వాటికే మెరుపు ఎక్కువ.", en: "Fake gold glitters the most." },
  { text: "కాకి పిల్ల కాకికి ముద్దు", meaning: "ఎవరి బిడ్డలు వారికి ముద్దు.", en: "To the crow, its own chick is lovely." },
  { text: "కాగల కార్యం గంధర్వులే తీర్చారు", meaning: "మనం చేయాల్సిన పని వేరెవరో అనుకోకుండా చేసిపెట్టారు.", en: "The job that had to be done was done by the celestials." },
  { text: "కాపురం చేసే కళ కాళ్ళ పారాణి దగ్గరే తెలుస్తుంది", meaning: "ఎవరి తీరైనా మొదట్లోనే బయటపడుతుంది.", en: "How the marriage will go shows while the bridal henna is still on the feet." },
  { text: "కాలు కాలిన పిల్లిలా", meaning: "కంగారుగా, అశాంతిగా అటూ ఇటూ తిరగడం.", en: "Like a cat with a burnt paw — restless." },
  { text: "కాలం కలిసి రాకపోతే కర్రే పామవుతుంది", meaning: "కాలం బాగోలేకపోతే మామూలు విషయాలు కూడా ఆపదలుగా మారతాయి.", en: "When times are bad, even a stick turns into a snake." },
  { text: "కాలం కలిసి వస్తే ఏట్లో వేసినా ఎదురొస్తుంది", meaning: "కాలం కలిసొస్తే పోగొట్టుకున్నది కూడా తిరిగి వస్తుంది.", en: "When times are good, what you throw in the river floats back to you." },
  { text: "కాలు జారితే తీసుకోగలం కానీ నోరు జారితే తీసుకోలేం", meaning: "జారిన మాటను వెనక్కి తీసుకోలేం; ఆలోచించి మాట్లాడాలి.", en: "A slip of the foot can be recovered, a slip of the tongue cannot." },
  { text: "కాసే చెట్టుకే రాళ్ళ దెబ్బలు", meaning: "ఉపయోగపడేవారే ఎక్కువ విమర్శలు, ఇబ్బందులు ఎదుర్కొంటారు.", en: "Only the fruit-bearing tree gets stoned." },
  { text: "కుక్క కాటుకు చెప్పు దెబ్బ", meaning: "దుష్టులకు తగిన సమాధానం అదే రీతిలో ఇవ్వాలి.", en: "A slipper-blow for a dog-bite — tit for tat." },
  { text: "కుక్క తోక పట్టుకుని గోదావరి ఈదినట్లు", meaning: "పనికిరాని ఆధారంతో పెద్ద పని చేయబోవడం.", en: "Trying to swim the Godavari holding a dog's tail." },
  { text: "కుక్క తోక వంకర", meaning: "స్వభావం ఎంత ప్రయత్నించినా మారదు.", en: "A dog's tail stays crooked." },
  { text: "కూర్చుని తింటే కొండలైనా కరుగుతాయి", meaning: "సంపాదించకుండా ఖర్చు చేస్తుంటే ఎంత సంపదైనా కరిగిపోతుంది.", en: "Sit and eat, and even mountains of wealth melt away." },
  { text: "కూసే గాడిద వచ్చి మేసే గాడిదను చెడగొట్టిందట", meaning: "పని చేసేవారిని పనికిమాలినవారు చెడగొట్టడం.", en: "The braying donkey came and spoiled the grazing one." },
  { text: "కొండ నాలుకకు మందు వేస్తే ఉన్న నాలుక ఊడినట్లు", meaning: "చిన్న సమస్య తీర్చబోయి పెద్ద నష్టం తెచ్చుకోవడం.", en: "Treating the uvula and losing the tongue." },
  { text: "కొండను తవ్వి ఎలుకను పట్టినట్లు", meaning: "ఎంతో కష్టపడినా దక్కింది కొంచెమే.", en: "Digging up a mountain to catch a mouse." },
  { text: "కొండముచ్చు పెళ్ళికి కోతి పేరంటాలు", meaning: "ఒకే రకం వాళ్ళు కలవడం.", en: "Monkeys as guests at the langur's wedding — birds of a feather." },
  { text: "కొత్త బిచ్చగాడు పొద్దెరుగడు", meaning: "కొత్తగా మొదలుపెట్టినవాడు అతి ఉత్సాహంతో సమయం సందర్భం చూడడు.", en: "A new beggar doesn't know the time of day." },
  { text: "కొత్త ఒక వింత, పాత ఒక రోత", meaning: "కొత్తది ఆకర్షిస్తుంది, పాతది విసుగనిపిస్తుంది.", en: "The new is a wonder, the old a bore." },
  { text: "కొన్నది వంకాయ, కొసరు గుమ్మడికాయ", meaning: "అసలు కన్నా అదనంగా అడిగేది పెద్దది.", en: "Bought a brinjal, asked for a pumpkin as the free extra." },
  { text: "కోరి కొరివితో తల గోక్కున్నట్టు", meaning: "కోరి కోరి ఆపద తెచ్చుకోవడం.", en: "Scratching your head with a burning stick by choice." },
  { text: "కోటి విద్యలు కూటి కొరకే", meaning: "ఎన్ని విద్యలు నేర్చినా అవి బతుకుతెరువు కోసమే.", en: "A crore of skills, all for a meal." },
  { text: "కోడలికి బుద్ధి చెప్పి అత్త తెడ్డు నాకిందట", meaning: "ఇతరులకు నీతులు చెప్పి తానే అదే తప్పు చేయడం.", en: "Lectured her daughter-in-law, then licked the ladle herself." },
  { text: "కోడిగుడ్డు మీద ఈకలు పీకే రకం", meaning: "లేని లోపాలు వెతికేవాడు.", en: "The kind who plucks feathers off an egg — a nitpicker." },
  { text: "కోతికి కొబ్బరికాయ దొరికినట్లు", meaning: "విలువ తెలియనివారికి విలువైనది దొరకడం.", en: "A monkey getting a coconut." },
  { text: "కృషితో నాస్తి దుర్భిక్షం", meaning: "కష్టపడి పనిచేసేవారికి కరువు ఉండదు.", en: "Where there is hard work, there is no famine." },

  // గ
  { text: "గంగిగోవు పాలు గరిటెడైనను చాలు", meaning: "మంచిది కొంచెమైనా చాలు; చెడ్డది ఎంతున్నా వృథా (వేమన).", en: "A ladleful of a good cow's milk is enough." },
  { text: "గంతకు తగ్గ బొంత", meaning: "ఒకరికొకరు తగినట్టుగా ఉండటం.", en: "A quilt to match the sack — a fitting pair." },
  { text: "గతి లేనమ్మకు గంజే పానకం", meaning: "ఏమీ లేనివారికి ఉన్నదే పరమాన్నం.", en: "To the destitute, rice-water is a sweet drink." },
  { text: "గాజుల బేరం భోజనానికి సరి", meaning: "సంపాదన కేవలం ఖర్చులకే సరిపోవడం.", en: "The bangle trade just covers the seller's meals." },
  { text: "గాడిదకేం తెలుసు గంధపు వాసన", meaning: "అర్హత లేనివారికి విలువైనవాటి గొప్పతనం తెలియదు.", en: "What does a donkey know of the scent of sandalwood?" },
  { text: "గాలిలో దీపం పెట్టి దేవుడా నీదే భారం అన్నాడట", meaning: "తాను జాగ్రత్త పడకుండా భారమంతా దేవుడి మీద వేయడం.", en: "Put the lamp in the wind and said, 'God, it's up to you.'" },
  { text: "గుంపులో గోవిందా", meaning: "అందరితో పాటు కలిసిపోవడం, తనదంటూ ప్రత్యేకత లేకపోవడం.", en: "Just another 'Govinda' in the crowd." },
  { text: "గుడ్డి కన్నా మెల్ల నయం", meaning: "ఏమీ లేకపోవడం కన్నా ఏదో కొంత ఉండటం మేలు.", en: "A squint is better than blindness." },
  { text: "గుడ్డు వచ్చి పిల్లను వెక్కిరించినట్టు", meaning: "అనుభవం లేనివాడు అనుభవజ్ఞుడిని వెక్కిరించడం.", en: "The egg mocking the chick." },
  { text: "గుడ్డెద్దు చేలో పడినట్లు", meaning: "దారీతెన్నూ లేకుండా అడ్డదిడ్డంగా ప్రవర్తించడం.", en: "Like a blind ox loose in a field." },
  { text: "గుడ్డివాడికి కుంటివాడి సాయం", meaning: "ఒకరి లోపాన్ని మరొకరు పూడ్చుకుంటూ కలిసి పనిచేయడం.", en: "The lame guiding the blind — each making up for the other." },
  { text: "గుమ్మడికాయల దొంగ అంటే భుజాలు తడుముకున్నట్టు", meaning: "తప్పు చేసినవాడు తనంతట తానే బయటపడటం.", en: "Hearing 'pumpkin thief!', he felt his shoulders — a guilty conscience gives itself away." },
  { text: "గురివింద గింజ తన నలుపెరుగదు", meaning: "తన లోపాలు తెలుసుకోకుండా ఇతరులను విమర్శించడం.", en: "The rosary pea doesn't see its own black spot." },
  { text: "గుర్రం గుడ్డిదైనా దాణాకు తక్కువ లేదు", meaning: "పనికి పనికిరాకపోయినా తిండికి మాత్రం ముందుండటం.", en: "The horse may be blind, but it never misses its feed." },
  { text: "గుర్రపు పిల్లకు గుగ్గిళ్ళు తినడం నేర్పాలా", meaning: "సహజంగా వచ్చేది ఎవరూ నేర్పనక్కర్లేదు.", en: "Must a foal be taught to eat gram?" },
  { text: "గోటితో పోయేదానికి గొడ్డలెందుకు", meaning: "చిన్నగా తీరే పనికి పెద్ద ప్రయత్నం అక్కర్లేదు.", en: "Why an axe for what a fingernail can do?" },
  { text: "గోతికాడ నక్కలా", meaning: "అవకాశం కోసం కాచుకుని ఉండటం.", en: "Like a fox waiting by the pit." },
  { text: "గోరంత ఆలస్యం కొండంత నష్టం", meaning: "చిన్న ఆలస్యం పెద్ద నష్టం తెస్తుంది.", en: "A nail's worth of delay, a mountain of loss." },
  { text: "గోరుచుట్టు మీద రోకటిపోటు", meaning: "ఉన్న బాధ మీద మరో దెబ్బ.", en: "A pestle blow on a sore fingernail — insult on injury." },
  { text: "గొంతెమ్మ కోరికలు", meaning: "తీరని, అతి పెద్ద కోరికలు.", en: "Gontemma's wishes — impossible demands." },

  // చ
  { text: "చక్కనమ్మ చిక్కినా అందమే", meaning: "మంచిది ఏ స్థితిలోనైనా బాగుంటుంది.", en: "A beauty is lovely even when she grows thin." },
  { text: "చచ్చినవాడి పెళ్ళికి వచ్చిందే కట్నం", meaning: "ఎలాగూ పోయేదాంట్లో దక్కినదే లాభం.", en: "At a dead man's wedding, whatever dowry comes is profit." },
  { text: "చదవేస్తే ఉన్న మతి పోయినట్లు", meaning: "చదువు వల్ల ఉన్న లోకజ్ఞానం కూడా పోవడం.", en: "Studied and lost what sense he had." },
  { text: "చదువుకున్నవాడికంటే చాకలివాడు మేలు", meaning: "పుస్తక జ్ఞానం కన్నా లోకజ్ఞానం గొప్పది.", en: "Better the washerman than the scholar — practical sense beats book learning." },
  { text: "చద్దన్నం తిన్నమ్మ మొగుడి ఆకలెరుగదు", meaning: "తను సుఖంగా ఉన్నవాడికి ఇతరుల బాధ తెలియదు.", en: "She who has eaten doesn't feel her husband's hunger." },
  { text: "చనిపోయిన వారి కళ్ళు చారెడు", meaning: "పోయినవారిని అతిగా పొగడటం.", en: "The dead always had big beautiful eyes." },
  { text: "చల్లకొచ్చి ముంత దాచినట్లు", meaning: "అడగడానికి వచ్చి సిగ్గుపడి అసలు విషయం దాచడం.", en: "Came for buttermilk, but hides the pot." },
  { text: "చాప కింద నీరులా", meaning: "ఎవరికీ తెలియకుండా నెమ్మదిగా వ్యాపించడం.", en: "Like water seeping under a mat." },
  { text: "చారాణా కోడికి బారాణా మసాలా", meaning: "అసలు కన్నా దానికయ్యే అదనపు ఖర్చు ఎక్కువ.", en: "Twelve annas of spice for a four-anna chicken." },
  { text: "చావు తప్పి కన్ను లొట్టబోయినట్లు", meaning: "పెద్ద ప్రమాదం తప్పినా ఎంతో కొంత నష్టం జరగడం.", en: "Escaped death but lost an eye." },
  { text: "చింత చచ్చినా పులుపు చావలేదు", meaning: "స్థితి పోయినా పాత బడాయి, అహంకారం పోకపోవడం.", en: "The tamarind tree is dead, but not its sourness." },
  { text: "చిత్తశుద్ధి లేని శివపూజలేల", meaning: "మనసు లేని భక్తి, పూజ వృథా (వేమన).", en: "Why worship without a pure heart?" },
  { text: "చిన్న పామునైనా పెద్ద కర్రతో కొట్టాలి", meaning: "చిన్న ప్రమాదాన్నైనా తక్కువ అంచనా వేయకూడదు.", en: "Even a small snake should be struck with a big stick." },
  { text: "చిలికి చిలికి గాలివాన అయినట్లు", meaning: "చిన్న విషయం పెరిగి పెరిగి పెద్ద గొడవవడం.", en: "A drizzle that grew into a storm." },
  { text: "చూసి రమ్మంటే కాల్చి వచ్చినట్టు", meaning: "చెప్పిన దానికి మించి చేయడం (హనుమంతుడు లంకను కాల్చినట్టు).", en: "Sent to have a look, came back having set it on fire." },
  { text: "చెట్టు పేరు చెప్పి కాయలమ్మినట్లు", meaning: "పెద్దల, ఇతరుల పేరు చెప్పుకుని లాభం పొందడం.", en: "Selling fruit on the tree's reputation." },
  { text: "చెడపకురా చెడేవు", meaning: "ఇతరులకు కీడు తలపెడితే నీకే కీడు జరుగుతుంది.", en: "Don't ruin others — you'll be ruined." },
  { text: "చెప్పేవాడికి వినేవాడు లోకువ", meaning: "ఊరికే వినేవాళ్ళు ఉంటే చెప్పేవాడికి అలుసు.", en: "The listener is always cheap to the talker." },
  { text: "చెప్పితే వినని వాడిని చెడిపోనివ్వాలి", meaning: "మంచి మాట వినని వాడికి అనుభవమే గుణపాఠం.", en: "Let the one who won't listen learn by falling." },
  { text: "చెముడా అంటే మొగుడా అన్నట్టు", meaning: "ఒకటి అడిగితే ఇంకొకటి జవాబు చెప్పడం.", en: "Asked 'are you deaf?', she answered 'husband?'" },
  { text: "చెవిటివాడి ముందు శంఖం ఊదినట్లు", meaning: "విననివాడికి చెప్పడం వృథా.", en: "Blowing a conch before the deaf." },
  { text: "చెవిలో జోరీగలా", meaning: "మాటిమాటికీ విసిగించడం.", en: "Like a gnat buzzing in the ear." },
  { text: "చేతకాక మంగళవారం అన్నాడట", meaning: "చేతకాని పనికి సాకులు చెప్పడం.", en: "Couldn't do it, so said 'it's Tuesday' — making excuses." },
  { text: "చేతకానమ్మకే చేష్టలెక్కువ", meaning: "పని రానివాళ్ళకే హడావుడి ఎక్కువ.", en: "The unskilled make the most fuss." },
  { text: "చేతులు కాలాక ఆకులు పట్టుకున్నట్టు", meaning: "నష్టం జరిగిపోయాక జాగ్రత్త పడటం.", en: "Reaching for leaves after the hands are burnt." },
  { text: "చెరువు మీద అలిగి స్నానం చేయనట్లు", meaning: "ఇతరుల మీద కోపంతో తనకే నష్టం చేసుకోవడం.", en: "Angry with the lake, so refuses to bathe." },

  // జ
  { text: "జగమెరిగిన బ్రాహ్మణుడికి జంధ్యమేల", meaning: "అందరికీ తెలిసినవాడికి గుర్తింపు, పరిచయం అక్కర్లేదు.", en: "A Brahmin known to the world needs no sacred thread to prove it." },
  { text: "జన్మకో శివరాత్రి", meaning: "ఎప్పుడో ఒకసారి, అరుదుగా జరిగేది.", en: "One Shivaratri in a lifetime — once in a blue moon." },
  { text: "జిహ్వకో రుచి, పుర్రెకో బుద్ధి", meaning: "ఒక్కొక్కరిది ఒక్కో అభిరుచి, ఒక్కో ఆలోచన.", en: "Each tongue its taste, each head its mind." },
  { text: "జీలకర్రలో కర్రా లేదు, నేతిబీరలో నెయ్యీ లేదు", meaning: "పేరుకే తప్ప అసలు విషయం లేదు.", en: "No stick in cumin, no ghee in the ghee-gourd — only in name." },
  { text: "జుట్టున్నమ్మ ఏ కొప్పు పెట్టినా అందమే", meaning: "వనరులు ఉన్నవాళ్ళు ఏం చేసినా బాగుంటుంది.", en: "One with long hair looks good in any style." },
  { text: "జోగి జోగి రాసుకుంటే బూడిద రాలినట్లు", meaning: "లేనివాళ్ళు ఇద్దరు కలిస్తే ఒరిగేదేమీ లేదు.", en: "When two ascetics rub together, only ash falls." },
  { text: "జలుబుకు మందు తింటే వారం, తినకపోతే ఏడు రోజులు", meaning: "కొన్ని సమస్యలు ఏం చేసినా తమ సమయం తీసుకునే పోతాయి.", en: "A cold lasts a week with medicine and seven days without." },

  // డ, ఢ
  { text: "డబ్బు ఏమైనా చెట్లకు కాస్తుందా", meaning: "డబ్బు కష్టపడితేనే వస్తుంది; జాగ్రత్తగా ఖర్చు పెట్టాలి.", en: "Does money grow on trees?" },
  { text: "డబ్బుకు లోకం దాసోహం", meaning: "డబ్బు ఉంటే లోకమంతా వంగి సలాం చేస్తుంది.", en: "The world bows to money." },
  { text: "డబ్బు ఇవ్వనివాడు ముందు పడవ ఎక్కుతాడు", meaning: "ఖర్చు పెట్టనివాడే లాభం కోసం అందరికంటే ముందుంటాడు.", en: "The one who won't pay the fare is first into the boat." },
  { text: "ఢిల్లీకి రాజైనా తల్లికి కొడుకే", meaning: "ఎంత గొప్పవాడైనా తల్లి ముందు బిడ్డే.", en: "Even the king of Delhi is just a son to his mother." },

  // త
  { text: "తల్లిని మించిన దైవం లేదు", meaning: "తల్లి కంటే గొప్ప దైవం లేదు.", en: "There is no god greater than a mother." },
  { text: "తండ్రి తవ్విన నుయ్యి అని అందులో పడి చావచ్చునా", meaning: "పెద్దలది అని ఏదైనా గుడ్డిగా అనుసరించకూడదు.", en: "Should you drown in a well just because your father dug it?" },
  { text: "తక్కువ నోములు నోచి ఎక్కువ ఫలం రమ్మంటే వస్తుందా", meaning: "కష్టానికి తగ్గట్టే ఫలితం; కొంచెం చేసి ఎక్కువ ఆశించకూడదు.", en: "Can small efforts bring big rewards?" },
  { text: "తగిలిన కాలికే తగులుతుంది", meaning: "దెబ్బ తగిలిన చోటే మళ్ళీ మళ్ళీ తగులుతుంది — కష్టాల మీద కష్టాలు.", en: "It's always the hurt foot that gets knocked again." },
  { text: "తడిగుడ్డతో గొంతులు కోసేవాడు", meaning: "తియ్యగా మాట్లాడుతూనే తెలియకుండా హాని చేసేవాడు.", en: "One who cuts throats with a wet cloth — harm with a smile." },
  { text: "తంతే బూరెల బుట్టలో పడ్డట్టు", meaning: "కీడు జరగబోయి అనుకోకుండా మేలు జరగడం.", en: "Kicked, and landed in a basket of sweets." },
  { text: "తనది కాకపోతే కాశీ దాకా దేకమన్నాడట", meaning: "ఇతరుల కష్టం, ఇతరుల సొమ్ము అంటే లెక్కలేకపోవడం.", en: "If it's not his own, he'll say 'crawl all the way to Kashi'." },
  { text: "తమలపాకుతో నువ్వొకటిస్తే తలుపు చెక్కతో నేనొకటిస్తా", meaning: "చిన్న దెబ్బకు పెద్ద దెబ్బతో బదులివ్వడం.", en: "Hit me with a betel leaf and I'll hit you with a door plank." },
  { text: "తల ప్రాణం తోకకు వచ్చినట్లు", meaning: "తీవ్రంగా కష్టపడి, ప్రాణం పోయినంత పని కావడం.", en: "Life came from head to tail — utterly exhausted." },
  { text: "తాను వలచినది రంభ, తాను మునిగినది గంగ", meaning: "తనకు నచ్చినదే గొప్పదనుకోవడం.", en: "The one I love is a celestial beauty; the water I bathe in is the Ganga." },
  { text: "తాను పట్టిన కుందేటికి మూడే కాళ్ళు", meaning: "తప్పని తెలిసినా తన మాటే నెగ్గాలనే మొండితనం.", en: "The hare I caught has only three legs — stubbornly insisting on being right." },
  { text: "తానొకటి తలిస్తే దైవమొకటి తలచాడు", meaning: "మనం అనుకున్నది ఒకటి, జరిగేది మరొకటి.", en: "Man proposes, God disposes." },
  { text: "తాంబూలాలిచ్చేశాను, ఇక తన్నుకు చావండి", meaning: "తన బాధ్యత తీర్చుకుని, ఆ తర్వాత ఏమైనా తనకు సంబంధం లేదనడం.", en: "I've handed over the betel — now fight it out yourselves." },
  { text: "తాను చెడ్డ కోతి వనమెల్లా చెరిచింది", meaning: "చెడిపోయినవాడు తనతో పాటు అందరినీ చెడగొడతాడు.", en: "The monkey that went bad spoiled the whole forest." },
  { text: "తాటాకు చప్పుళ్ళకు కుందేళ్ళు బెదరవు", meaning: "ఒట్టి బెదిరింపులకు భయపడేది లేదు.", en: "Hares aren't scared by the rustle of palm leaves." },
  { text: "తాటిచెట్టు ఎందుకెక్కావంటే దూడ గడ్డి కోసమన్నాడట", meaning: "తప్పును కప్పిపుచ్చడానికి పొంతన లేని సాకు.", en: "Asked why he climbed the toddy palm, he said 'grass for the calf'." },
  { text: "తాటిచెట్టు కింద మజ్జిగ తాగినా కల్లు అంటారు", meaning: "చెడ్డ చోట ఉంటే మంచి పని చేసినా అనుమానిస్తారు.", en: "Drink buttermilk under a toddy palm and they'll say it's toddy." },
  { text: "తాడిని తన్నేవాడుంటే వాడి తలదన్నేవాడుంటాడు", meaning: "ఎంత గొప్పవాడినైనా మించినవాడు ఉంటాడు.", en: "For every man who can kick a palm tree, there's one who can kick his head." },
  { text: "తాతకు దగ్గులు నేర్పినట్టు", meaning: "అనుభవజ్ఞుడికే నేర్పబోవడం.", en: "Teaching grandpa how to cough." },
  { text: "తాదూర సందు లేదు, మెడకో డోలు", meaning: "తనకే చోటు లేదు, పైగా అదనపు భారం.", en: "No room to squeeze in himself, yet a drum round his neck." },
  { text: "తానా అంటే తందానా", meaning: "ఆలోచించకుండా ఎదుటివారి మాటకు వత్తాసు పలకడం.", en: "Say 'taana' and he sings 'tandaana' — a yes-man." },
  { text: "తామరాకు మీద నీటిబొట్టులా", meaning: "దేనికీ అంటకుండా, అంటీముట్టనట్టు ఉండటం.", en: "Like a water drop on a lotus leaf — untouched, detached." },
  { text: "తింటే గారెలే తినాలి, వింటే భారతమే వినాలి", meaning: "ఏదైనా చేస్తే ఉత్తమమైనదే చేయాలి.", en: "If you eat, eat vadas; if you listen, listen to the Mahabharata." },
  { text: "తిండికి తిమ్మరాజు, పనికి పోతరాజు", meaning: "తినడంలో ముందు, పనిలో వెనక.", en: "A king at the table, a runaway at work." },
  { text: "తిక్కలవాళ్ళు తిరునాళ్ళకెళ్తే ఎక్కనూ దిగనూ సరిపోయిందట", meaning: "ప్రణాళిక లేకపోతే సమయమంతా వృథా.", en: "The scatterbrains went to the fair and spent it all getting on and off the cart." },
  { text: "తినగ తినగ వేము తియ్యగనుండు", meaning: "సాధన చేస్తే కష్టమైనది కూడా సులభం, ఇష్టం అవుతుంది (వేమన).", en: "Keep eating neem and it turns sweet." },
  { text: "తిన్నింటి వాసాలు లెక్కపెట్టినట్లు", meaning: "ఆశ్రయం ఇచ్చినవారికే ద్రోహం చేయడం.", en: "Counting the rafters of the house that fed you." },
  { text: "తీగ లాగితే డొంకంతా కదిలినట్లు", meaning: "చిన్న విషయం కదిలిస్తే పెద్ద వ్యవహారం బయటపడటం.", en: "Pull one vine and the whole bush shakes." },
  { text: "తుంటి మీద కొడితే పళ్ళు రాలాయి", meaning: "కారణానికీ ఫలితానికీ పొంతన లేకపోవడం.", en: "Hit on the hip, and the teeth fell out." },
  { text: "తెలిసే వరకూ బ్రహ్మవిద్య, తెలిశాక కూసువిద్య", meaning: "తెలియనప్పుడు కష్టం అనిపించేది తెలిశాక చాలా సులభం.", en: "A great mystery until you learn it, child's play afterwards." },
  { text: "తేలు కుట్టిన దొంగలా", meaning: "బాధ ఉన్నా బయటికి చెప్పుకోలేని స్థితి.", en: "Like a thief stung by a scorpion — can't even cry out." },
  { text: "తొండ ముదిరి ఊసరవెల్లి అయినట్టు", meaning: "చెడ్డవాడు ముదిరి మరింత కపటిగా మారడం.", en: "The lizard grew up into a chameleon." },
  { text: "తోక తొక్కిన పాములా", meaning: "ఒక్కసారిగా రెచ్చిపోవడం.", en: "Like a snake whose tail was stepped on." },
  { text: "తోచీ తోచనమ్మ తోటికోడలు పుట్టింటికి వెళ్ళినట్టు", meaning: "పనిలేక అనవసరమైన పనుల్లో తలదూర్చడం.", en: "With nothing to do, she escorted her sister-in-law to her parents' home." },

  // ద, ధ
  { text: "దంచినమ్మకు బొక్కిందే దక్కుదల", meaning: "కష్టపడినవాడికి చివరకు దక్కేది కొంచెమే.", en: "The woman who pounds the grain keeps only what she nibbles." },
  { text: "దరిద్రుడి పెళ్ళికి వడగళ్ళ వాన", meaning: "లేనివాడికి కష్టాల మీద కష్టాలు.", en: "A hailstorm at the poor man's wedding." },
  { text: "దాసుని తప్పు దండంతో సరి", meaning: "చిన్న తప్పుకు క్షమాపణ చాలు.", en: "A servant's mistake is settled with a bow." },
  { text: "దిక్కులేనివారికి దేవుడే దిక్కు", meaning: "ఎవరూ లేనివారికి దేవుడే ఆసరా.", en: "God is the refuge of those who have no one." },
  { text: "దిగితేనేగానీ లోతు తెలియదు", meaning: "పనిలోకి దిగితేనే అసలు కష్టం తెలుస్తుంది.", en: "You only know the depth once you step in." },
  { text: "దినదిన గండం నూరేళ్ళ ఆయుష్షు", meaning: "రోజూ ప్రమాదాలు ఎదురైనా బతుకు సాగిపోవడం.", en: "Danger every day, yet a life of a hundred years." },
  { text: "దీపం ఉండగానే ఇల్లు చక్కబెట్టుకోవాలి", meaning: "అవకాశం ఉండగానే పనులు చక్కబెట్టుకోవాలి.", en: "Tidy the house while the lamp is still lit — make hay while the sun shines." },
  { text: "దున్నపోతు మీద వాన కురిసినట్లు", meaning: "ఎంత చెప్పినా చలనం లేకపోవడం.", en: "Like rain on a buffalo — no effect at all." },
  { text: "దురాశ దుఃఖానికి చేటు", meaning: "అత్యాశ దుఃఖాన్ని తెస్తుంది.", en: "Greed leads to grief." },
  { text: "దూరపు కొండలు నునుపు", meaning: "దూరం నుంచి చూస్తే ఏదైనా అందంగా, సులభంగా కనిపిస్తుంది.", en: "Distant hills look smooth." },
  { text: "దెయ్యాలు వేదాలు వల్లించినట్లు", meaning: "దుర్మార్గులు నీతులు చెప్పడం.", en: "Devils reciting the Vedas." },
  { text: "దేవుడు వరమిచ్చినా పూజారి వరమివ్వడు", meaning: "పైవాళ్ళు ఒప్పుకున్నా మధ్యవాళ్ళు అడ్డుపడటం.", en: "God grants the boon, but the priest won't." },
  { text: "దొంగలు పడ్డ ఆరు నెలలకు కుక్కలు మొరిగినట్లు", meaning: "సమయం దాటిపోయాక స్పందించడం.", en: "The dogs barked six months after the burglary." },
  { text: "దొంగ చేతికి తాళాలిచ్చినట్లు", meaning: "నమ్మకూడనివారికి బాధ్యత అప్పగించడం.", en: "Handing the keys to a thief." },
  { text: "దొందూ దొందే", meaning: "ఇద్దరూ ఒకే రకం.", en: "Both are the same." },
  { text: "దొరికితే దొంగలు, లేకుంటే దొరలు", meaning: "పట్టుబడనంత వరకు అందరూ పెద్దమనుషులే.", en: "Thieves if caught, gentlemen if not." },
  { text: "ధర్మో రక్షతి రక్షితః", meaning: "ధర్మాన్ని కాపాడేవారిని ధర్మమే కాపాడుతుంది.", en: "Dharma protects those who protect it." },
  { text: "ధైర్యే సాహసే లక్ష్మీ", meaning: "ధైర్యం, సాహసం ఉన్నవారికే సంపద వరిస్తుంది.", en: "Fortune favours the brave." },

  // న
  { text: "నక్క పుట్టి నాలుగు వారాలు కాలేదు, ఇంత పెద్ద గాలివాన ఎప్పుడూ చూడలేదన్నదట", meaning: "అనుభవం లేకపోయినా పెద్ద పెద్ద మాటలు చెప్పడం.", en: "A fox not four weeks old said it had never seen such a storm in its life." },
  { text: "నడమంత్రపు సిరి నరము మీద పుండు", meaning: "అకస్మాత్తుగా వచ్చిన సంపద అహంకారాన్ని, బాధను తెస్తుంది.", en: "Sudden wealth is like a boil on a nerve." },
  { text: "నడిచే కాలు, వాగే నోరు ఊరుకోవు", meaning: "తిరిగేవాడు, వాగేవాడు ఊరికే ఉండలేరు.", en: "A wandering foot and a chattering mouth never rest." },
  { text: "నలుగురితో నారాయణా", meaning: "అందరితో పాటు మనమూ; అందరికీ జరిగేదే మనకూ.", en: "Whatever happens to all, happens to me too." },
  { text: "నవ్విన నాపచేనే పండుతుంది", meaning: "ఎవరిని చూసి నవ్వుతామో వారే ముందుకొస్తారు; ఎవరినీ చులకన చేయకూడదు.", en: "The barren field you laughed at will yield a harvest." },
  { text: "నవ్వు నాలుగు విధాల చేటు", meaning: "సందర్భం లేని నవ్వు అనేక విధాల నష్టం తెస్తుంది.", en: "Untimely laughter harms in four ways." },
  { text: "నాడా దొరికిందని గుర్రాన్ని కొన్నట్లు", meaning: "చిన్నదానికోసం పెద్ద ఖర్చు పెట్టడం.", en: "Found a horseshoe, so bought a horse." },
  { text: "నిండా మునిగినవాడికి చలేంటి", meaning: "పూర్తిగా కష్టాల్లో మునిగినవాడికి ఇంకో కష్టం లెక్కలోది కాదు.", en: "What's the cold to one already soaked through?" },
  { text: "నిండుకుండ తొణకదు", meaning: "నిజమైన జ్ఞానులు నిశ్శబ్దంగా, నిబ్బరంగా ఉంటారు.", en: "A full pot doesn't splash." },
  { text: "నిజం నిప్పులాంటిది", meaning: "నిజాన్ని ఎంత దాచినా అది బయటపడుతుంది.", en: "Truth is like fire." },
  { text: "నిజం నిలకడ మీద తెలుస్తుంది", meaning: "కొంతకాలం గడిస్తే నిజం దానంతటదే తెలుస్తుంది.", en: "Truth comes out in time." },
  { text: "నిత్య కళ్యాణం, పచ్చ తోరణం", meaning: "ఎప్పుడూ శుభకార్యాలతో సందడిగా ఉండటం.", en: "A wedding every day, green garlands always up." },
  { text: "నిప్పు ముట్టనిదే చేయి కాలదు", meaning: "అనుభవంలోకి వస్తేనే అసలు తెలుస్తుంది.", en: "The hand doesn't burn until it touches fire." },
  { text: "నిప్పు లేనిదే పొగ రాదు", meaning: "కారణం లేకుండా పుకారు పుట్టదు.", en: "No smoke without fire." },
  { text: "నివురుగప్పిన నిప్పులా", meaning: "పైకి శాంతంగా ఉన్నా లోపల కోపం, శక్తి దాగి ఉండటం.", en: "Like embers under ash." },
  { text: "నీటిలో రాతలు రాసినట్లు", meaning: "నిలవని మాటలు, వృథా ప్రయత్నం.", en: "Writing on water." },
  { text: "నీతిలేని పొరుగు నిప్పుతో సమానం", meaning: "నీతి లేనివారి సాంగత్యం ప్రమాదకరం.", en: "A dishonest neighbour is like fire next door." },
  { text: "నువ్వు దంచు, నేను భుజాలెగరేస్తాను", meaning: "ఒకరు కష్టపడితే మరొకరు కష్టపడినట్టు నటించడం.", en: "You pound the grain; I'll heave my shoulders." },
  { text: "నూరు గొడ్లను తిన్న రాబందు ఒక్క గాలివానకు చస్తుంది", meaning: "ఎంత బలవంతుడైనా ఒక్క దెబ్బకు కూలిపోవచ్చు.", en: "The vulture that ate a hundred cattle dies in a single storm." },
  { text: "నేల విడిచి సాము చేసినట్లు", meaning: "ఆధారం లేకుండా, వాస్తవం విడిచి పనులు చేయడం.", en: "Doing stunts with no ground beneath." },
  { text: "నోరు మంచిదైతే ఊరు మంచిదవుతుంది", meaning: "మంచిగా మాట్లాడితే అందరూ మంచిగా ఉంటారు.", en: "A kind tongue makes a kind village." },
  { text: "నా కోడి కుంపటి లేకపోతే తెల్లవారదు అన్నట్టు", meaning: "తాను లేకపోతే ఏ పనీ జరగదనే అహంకారం.", en: "'Without my rooster and my stove, the sun won't rise!'" },
  { text: "నీరు పల్లమెరుగు, నిజం దేవుడెరుగు", meaning: "నీరు పల్లానికే పారుతుంది; నిజం దేవుడికే తెలుసు.", en: "Water knows the low ground; only God knows the truth." },

  // ప
  { text: "పండిత పుత్రః పరమ శుంఠః", meaning: "పండితుడి కొడుకు పండితుడు కావాలని లేదు.", en: "A scholar's son may be a dunce." },
  { text: "పక్కలో బల్లెం", meaning: "దగ్గరే ఉంటూ నిరంతరం ప్రమాదంగా మారేవాడు.", en: "A spear at one's side — a constant threat close by." },
  { text: "పచ్చకామెర్లవాడికి లోకమంతా పచ్చగా కనిపిస్తుంది", meaning: "మనసులో ఉన్నదాన్ని బట్టే లోకం కనిపిస్తుంది.", en: "To the jaundiced eye, everything looks yellow." },
  { text: "పని లేని మంగలి పిల్లి తల గొరిగినట్లు", meaning: "పనిలేక పనికిరాని పనులు చేయడం.", en: "An idle barber shaves the cat's head." },
  { text: "పరిగెత్తి పాలు తాగడం కంటే నిలబడి నీళ్ళు తాగడం మేలు", meaning: "హడావుడిగా ఎక్కువ సంపాదించడం కన్నా ప్రశాంతంగా కొంచెంతో తృప్తిపడటం మేలు.", en: "Better to drink water standing still than milk on the run." },
  { text: "పళ్ళూడగొట్టుకోవడానికి ఏ రాయైతేనేమి", meaning: "నష్టం ఖాయమైనప్పుడు ఏ దారైనా ఒకటే.", en: "To knock out your teeth, any stone will do." },
  { text: "పాడిందే పాడరా పాచిపళ్ళ దాసుడా", meaning: "చెప్పిందే మళ్ళీ మళ్ళీ చెప్పడం.", en: "Singing the same old song again and again." },
  { text: "పాపమని పాతచీర ఇస్తే ఇంటెనక్కెళ్ళి మూరలేసిందట", meaning: "సాయం పొంది కూడా కృతజ్ఞత లేకుండా లెక్కలేయడం.", en: "Given an old sari out of pity, she went behind the house to measure it." },
  { text: "పాలు నీళ్ళలా కలిసిపోయారు", meaning: "విడదీయలేనంతగా కలిసిపోవడం.", en: "Mixed like milk and water — inseparable." },
  { text: "పాము చావకూడదు, కర్ర విరగకూడదు", meaning: "ఎవరికీ నష్టం లేకుండా తెలివిగా పని చక్కబెట్టాలి.", en: "The snake must die without the stick breaking." },
  { text: "పిండి కొద్దీ రొట్టె", meaning: "పెట్టుబడిని బట్టే ఫలితం.", en: "The bread is only as big as the dough." },
  { text: "పిచ్చి పలు రకాలు, వెర్రి వేయి రకాలు", meaning: "మనుషుల పిచ్చిపనులు లెక్కలేనన్ని రకాలు.", en: "Madness comes in many forms, folly in a thousand." },
  { text: "పిచ్చివాడి చేతిలో రాయి", meaning: "అనర్హుడి చేతిలో అధికారం, ఆయుధం ప్రమాదకరం.", en: "A stone in a madman's hand." },
  { text: "పిచ్చుక మీద బ్రహ్మాస్త్రం", meaning: "చిన్న సమస్యకు అతి పెద్ద ఆయుధం వాడటం.", en: "Firing the ultimate weapon at a sparrow." },
  { text: "పిట్ట కొంచెం కూత ఘనం", meaning: "చిన్నవాడైనా మాటలు, ప్రతిభ గొప్పవి.", en: "A small bird with a big song." },
  { text: "పిల్లకాకికేం తెలుసు ఉండేలు దెబ్బ", meaning: "అనుభవం లేనివారికి ప్రమాదం విలువ తెలియదు.", en: "What does a young crow know of the slingshot?" },
  { text: "పిల్లికి చెలగాటం, ఎలుకకు ప్రాణసంకటం", meaning: "ఒకరికి ఆట, మరొకరికి ప్రాణాపాయం.", en: "Play for the cat, life and death for the mouse." },
  { text: "పుట్టుకతో వచ్చిన బుద్ధి పుడకలతో గానీ పోదు", meaning: "పుట్టుకతో వచ్చిన స్వభావం చితిలోనే పోతుంది.", en: "A nature one is born with leaves only on the funeral pyre." },
  { text: "పుణ్యం కొద్దీ పురుషుడు, దానం కొద్దీ బిడ్డలు", meaning: "మనం చేసుకున్న పుణ్యాన్ని బట్టే మనకు దక్కేవారు.", en: "Your spouse by your merit, your children by your charity." },
  { text: "పులిని చూసి నక్క వాత పెట్టుకున్నట్లు", meaning: "గొప్పవాళ్ళను గుడ్డిగా అనుకరించి నష్టపోవడం.", en: "The fox branded stripes on itself to look like the tiger." },
  { text: "పూజించిన పామే ప్రాణం తీసినట్లు", meaning: "నమ్మి ఆదరించినవారే ద్రోహం చేయడం.", en: "The very snake you worshipped took your life." },
  { text: "పెనం మీద నుంచి పొయ్యిలో పడ్డట్టు", meaning: "ఒక కష్టం తప్పించుకుని అంతకంటే పెద్ద కష్టంలో పడటం.", en: "Out of the frying pan into the fire." },
  { text: "పెరుగుట విరుగుట కొరకే", meaning: "మితిమీరి పెరిగినది పతనానికే దారి తీస్తుంది.", en: "What rises too high is bound to break." },
  { text: "పెళ్ళికి వెళ్తూ పిల్లిని చంకన పెట్టుకుని వెళ్ళినట్టు", meaning: "అనవసర భారాన్ని వెంటబెట్టుకుని తిరగడం.", en: "Going to a wedding with a cat under your arm." },
  { text: "పెదవులతో నవ్వుతూ నొసలతో వెక్కిరించడం", meaning: "పైకి మెచ్చుకుంటూ లోలోపల ఎగతాళి చేయడం.", en: "Smiling with the lips, sneering with the brow." },
  { text: "పేకాట పేకాటే, తమ్ముడు తమ్ముడే", meaning: "ఆట, వ్యాపారంలో బంధుత్వాలకు చోటు లేదు.", en: "Cards are cards, and brother is brother — no favours in the game." },
  { text: "పేనుకు పెత్తనమిస్తే తలంతా గొరిగిందట", meaning: "అల్పుడికి అధికారం ఇస్తే అనర్థం.", en: "Give a louse authority and it shaves the whole head." },
  { text: "పేరు గొప్ప ఊరు దిబ్బ", meaning: "పేరుకే గొప్ప, అసలు విషయం శూన్యం.", en: "A grand name, a village of rubbish." },
  { text: "పైన పటారం, లోన లొటారం", meaning: "పైకి ఆడంబరం, లోపల డొల్ల.", en: "Glitter outside, hollow within." },
  { text: "పొట్టివాడికి పుట్టెడు బుద్ధులు", meaning: "చిన్నవారైనా తెలివి ఎక్కువ.", en: "The short man has a sackful of wits." },
  { text: "పొమ్మనలేక పొగ పెట్టినట్లు", meaning: "నేరుగా వెళ్ళమనలేక పరోక్షంగా వెళ్ళగొట్టడం.", en: "Can't say 'leave', so fills the room with smoke." },
  { text: "పొరుగింటి పుల్లకూర రుచి", meaning: "మన దగ్గర ఉన్నదానికంటే ఇతరులదే గొప్పగా కనిపించడం.", en: "The neighbour's sour curry always tastes better." },

  // బ, భ
  { text: "బతకలేక బడిపంతులు", meaning: "వేరే దారి లేక ఏదో పని చేసుకుంటూ బతకడం (పాతకాలంలో బడిపంతుళ్ళ జీతాలు చాలా తక్కువ).", en: "Couldn't make a living, so became a schoolteacher — a job taken for lack of options." },
  { text: "బరితెగించిన కోడి బజార్లో గుడ్డు పెట్టిందట", meaning: "సిగ్గు విడిచినవారు బహిరంగంగానే ఏదైనా చేస్తారు.", en: "The shameless hen laid its egg in the marketplace." },
  { text: "బతికుంటే బలుసాకు తినవచ్చు", meaning: "ప్రాణం ఉంటే ఎలాగోలా బతకవచ్చు; ముందు ప్రాణం కాపాడుకో.", en: "Stay alive and you can live on wild greens." },
  { text: "బెండకాయ ముదిరినా, బ్రహ్మచారి ముదిరినా పనికిరావు", meaning: "కొన్నిటికి తగిన సమయం దాటిపోతే విలువ తగ్గుతుంది.", en: "An overripe okra and an ageing bachelor are both past their best." },
  { text: "బెల్లం చుట్టూ ఈగల్లా", meaning: "లాభం ఉన్న చోటికే అందరూ చేరడం.", en: "Like flies around jaggery." },
  { text: "బొంకరా బొంకరా పోలిగా అంటే టంగుటూరి మిరియం తాటికాయంత అన్నాడట", meaning: "అబద్ధం చెప్పమంటే మరీ అతిగా బొంకడం.", en: "Told to fib, Poligadu said a Tanguturi peppercorn is as big as a palm fruit." },
  { text: "బూడిదలో పోసిన పన్నీరు", meaning: "అనర్హులకు చేసినది వృథా.", en: "Rosewater poured on ashes — wasted effort." },
  { text: "బోడిగుండుకు మోకాలికి ముడి పెట్టినట్లు", meaning: "సంబంధం లేని రెండు విషయాలను కలిపి మాట్లాడటం.", en: "Tying a knot between a bald head and a knee." },
  { text: "భక్తి లేని పూజ పత్రి చేటు", meaning: "మనసు లేని పూజ ఆకుల దండగ.", en: "Worship without devotion only wastes the leaves." },

  // మ
  { text: "మంత్రాలకు చింతకాయలు రాలుతాయా", meaning: "ఒట్టి మాటలతో పనులు జరగవు; శ్రమ కావాలి.", en: "Do tamarinds fall from chanting spells?" },
  { text: "మందెక్కువైతే మజ్జిగ పలచనవుతుంది", meaning: "ఎక్కువమంది పంచుకుంటే ఒక్కొక్కరి వాటా తగ్గుతుంది.", en: "Too many people, and the buttermilk gets thin." },
  { text: "మనిషి మర్మం, మాను చేవ బయటికి తెలియవు", meaning: "మనిషి మనసు, చెట్టు లోపలి గట్టితనం పైకి కనిపించవు.", en: "A person's secrets and a tree's heartwood don't show outside." },
  { text: "మంచి మనిషికొక మాట, మంచి గొడ్డుకొక దెబ్బ", meaning: "బుద్ధిమంతుడికి ఒక్క మాట చాలు.", en: "A good man needs one word, a good ox one tap." },
  { text: "మంచమున్నంత వరకు కాళ్ళు చాపుకో", meaning: "ఆదాయానికి తగ్గట్టే ఖర్చు పెట్టాలి.", en: "Stretch your legs only as far as the cot allows." },
  { text: "మందుకని పంపిస్తే మాసికం నాటికి వచ్చాడట", meaning: "అత్యవసర పనిని అంతులేని ఆలస్యం చేయడం.", en: "Sent for medicine, he returned for the death anniversary." },
  { text: "మబ్బుల్లో నీళ్ళు చూసి ముంత ఒలకబోసుకున్నట్లు", meaning: "లేని దాని మీద ఆశతో ఉన్నది పోగొట్టుకోవడం.", en: "Saw rain clouds and poured out the water in the pot." },
  { text: "మా తాతలు నేతులు తాగారు, మా మూతులు వాసన చూడండి", meaning: "పూర్వీకుల గొప్పలు చెప్పుకుని బతకడం.", en: "Our grandfathers drank ghee — come, smell our lips." },
  { text: "మాటలు కోటలు దాటుతాయి కానీ కాలు గడప దాటదు", meaning: "మాటలే తప్ప చేతలు లేవు.", en: "Words leap over fortresses, but the feet never cross the threshold." },
  { text: "మింగ మెతుకు లేదు, మీసాలకు సంపెంగ నూనె", meaning: "తినడానికి లేకపోయినా ఆడంబరాలు.", en: "Not a grain to eat, yet perfumed oil for the moustache." },
  { text: "ముంజేతి కంకణానికి అద్దమేల", meaning: "స్పష్టంగా కనిపించేదానికి రుజువు అక్కర్లేదు.", en: "Why a mirror to see the bangle on your wrist?" },
  { text: "మునిగిపోయేవాడికి గడ్డిపోచ దొరికినట్లు", meaning: "ఆపదలో చిన్న ఆసరా కూడా గొప్పది.", en: "A drowning man clutching at a straw." },
  { text: "ముందు నుయ్యి వెనుక గొయ్యి", meaning: "రెండు వైపులా ప్రమాదం; ఎటూ తేల్చుకోలేని స్థితి.", en: "A well ahead, a pit behind." },
  { text: "ముందుంది ముసళ్ళ పండుగ", meaning: "అసలు కష్టాలు ఇంకా ముందున్నాయి.", en: "The real trouble is yet to come." },
  { text: "ముందొచ్చిన చెవుల కన్నా వెనకొచ్చిన కొమ్ములు వాడి", meaning: "తర్వాత వచ్చినవారు ముందున్నవారిని మించిపోవడం.", en: "The horns that came later are sharper than the ears that came first." },
  { text: "ముద్దొచ్చినప్పుడే చంకకెక్కాలి", meaning: "అవకాశం ఉన్నప్పుడే ఉపయోగించుకోవాలి.", en: "Climb onto the hip while you're still cute — seize the moment." },
  { text: "ముల్లును ముల్లుతోనే తీయాలి", meaning: "సమస్యను దానికి తగిన పద్ధతిలోనే పరిష్కరించాలి.", en: "A thorn is removed with a thorn." },
  { text: "మూల విగ్రహానికే ఈగలు తోలుతుంటే ఉత్సవ విగ్రహం ఊరేగింపు ఎప్పుడని అడిగినట్టు", meaning: "ప్రధాన అవసరాలే తీరనప్పుడు ఆడంబరాలు కోరడం.", en: "The main idol lies swatted by flies, and someone asks when the festival procession is." },
  { text: "మూలిగే నక్క మీద తాటిపండు పడ్డట్టు", meaning: "కష్టంలో ఉన్నవారికి మరో కష్టం.", en: "A palm fruit falling on a moaning fox." },
  { text: "మెరిసేదంతా బంగారం కాదు", meaning: "పైకి బాగా కనిపించేవన్నీ మంచివి కావు.", en: "All that glitters is not gold." },
  { text: "మొండివాడు రాజు కన్నా బలవంతుడు", meaning: "మొండివాడితో ఎవరూ నెగ్గలేరు.", en: "The stubborn man is stronger than the king." },
  { text: "మొక్కై వంగనిది మానై వంగునా", meaning: "చిన్నప్పుడే అలవాట్లు నేర్పాలి; పెద్దయ్యాక మారవు.", en: "What didn't bend as a sapling won't bend as a tree." },
  { text: "మొగుడు కొట్టినందుకు కాదు బాధ, తోటికోడలు నవ్వినందుకు", meaning: "దెబ్బ కంటే అవమానమే ఎక్కువ బాధిస్తుంది.", en: "It's not the blow that hurts, but the rival's laughter." },
  { text: "మొగుణ్ణి కొట్టి మొగసాలకెక్కినట్టు", meaning: "తప్పు చేసి తానే ముందుగా ఫిర్యాదు చేయడం.", en: "Beat the husband, then ran to complain first." },
  { text: "మోకాలికీ బోడిగుండుకూ ముడి వేసినట్టు", meaning: "సంబంధం లేని విషయాలను ముడిపెట్టడం.", en: "Knotting a knee to a bald head." },
  { text: "మోసేవాడికి తెలుస్తుంది కావడి బరువు", meaning: "కష్టం అనుభవించేవాడికే దాని తీవ్రత తెలుస్తుంది.", en: "Only the carrier knows the weight of the load." },
  { text: "మౌనం అర్ధాంగీకారం", meaning: "మాట్లాడకపోవడం సగం ఒప్పుకోలుతో సమానం.", en: "Silence is half consent." },
  { text: "మనసుంటే మార్గముంటుంది", meaning: "పట్టుదల ఉంటే దారి దొరుకుతుంది.", en: "Where there's a will, there's a way." },
  { text: "మనిషికో మాట, గొడ్డుకో దెబ్బ", meaning: "బుద్ధిమంతుడికి ఒక్క మాట చెబితే చాలు.", en: "One word for a person, one stroke for an ox." },

  // య, ర
  { text: "యథా రాజా తథా ప్రజా", meaning: "పాలకుడు ఎలా ఉంటే ప్రజలూ అలాగే ఉంటారు.", en: "As the king, so the people." },
  { text: "రాజు తలచుకుంటే దెబ్బలకు కొదవా", meaning: "అధికారం ఉన్నవాడు తలచుకుంటే ఏదైనా చేయగలడు.", en: "If the king so wishes, there's no shortage of blows." },
  { text: "రాజుల సొమ్ము రాళ్ళపాలు, దొరల సొమ్ము దొంగల పాలు", meaning: "అక్రమంగా కూడబెట్టిన సంపద నిలవదు.", en: "Kings' wealth goes to stones, lords' wealth to thieves." },
  { text: "రామాయణమంతా విని రాముడికి సీత ఏమవుతుందని అడిగినట్టు", meaning: "అంతా విని కూడా అసలు విషయం అర్థం చేసుకోకపోవడం.", en: "Heard the whole Ramayana and asked how Sita is related to Rama." },
  { text: "రామేశ్వరం వెళ్ళినా శనీశ్వరం వదలనట్టు", meaning: "ఎక్కడికి వెళ్ళినా దురదృష్టం వెంటాడటం.", en: "Went to Rameswaram, but Saturn's curse followed." },
  { text: "రెక్కాడితే గానీ డొక్కాడదు", meaning: "కష్టపడితే గానీ కడుపు నిండదు.", en: "Only if the arms move does the belly fill." },
  { text: "రెంటికీ చెడ్డ రేవడి", meaning: "రెండు అవకాశాలూ పోగొట్టుకోవడం.", en: "Lost on both sides." },
  { text: "రొట్టె విరిగి నేతిలో పడ్డట్లు", meaning: "అనుకోకుండా అదృష్టం కలిసిరావడం.", en: "The bread broke and fell into ghee." },
  { text: "రోగి కోరిందీ అదే, వైద్యుడు ఇచ్చిందీ అదే", meaning: "కోరుకున్నదే అనుకూలంగా దక్కడం.", en: "Just what the patient wanted, the doctor prescribed." },
  { text: "రోట్లో తల పెట్టి రోకటిపోటుకు వెరువ దీరునా", meaning: "సాహసం చేశాక ఆ కష్టాలకు భయపడకూడదు.", en: "Having put your head in the mortar, don't fear the pestle." },
  { text: "రోలు వెళ్ళి మద్దెలతో మొరపెట్టుకున్నట్టు", meaning: "బాధితుడు తనలాంటి మరో బాధితుడి దగ్గర మొరపెట్టుకోవడం.", en: "The mortar complaining to the drum — both get beaten." },
  { text: "రౌతు మెత్తనైతే గుర్రం మూడు కాళ్ళ మీద పరిగెడుతుంది", meaning: "నాయకుడు బలహీనుడైతే కిందివారు చులకన చేస్తారు.", en: "If the rider is soft, the horse runs on three legs." },
  { text: "రౌతు కొద్దీ గుర్రం", meaning: "నడిపేవాణ్ణి బట్టే నడిచేవారి తీరు.", en: "The horse is as good as its rider." },

  // ల
  { text: "లంఖణం పరమౌషధం", meaning: "ఉపవాసమే మంచి మందు.", en: "Fasting is the best medicine." },
  { text: "లేడికి లేచిందే పరుగు", meaning: "ఆలోచించకుండా వెంటనే పని మొదలుపెట్టడం.", en: "The deer runs the moment it stands." },
  { text: "లేని దాత కంటే ఉన్న లోభి నయం", meaning: "ఇవ్వలేని దాత కన్నా కొంచెమైనా ఇచ్చే పిసినారి మేలు.", en: "A miser who has is better than a donor who hasn't." },
  { text: "లోగుట్టు పెరుమాళ్ళకెరుక", meaning: "లోపలి రహస్యం దేవుడికే తెలుసు.", en: "Only the Lord knows the inside story." },

  // వ
  { text: "వండుకు తినేవాడికి ఒకటే కూర, అడుక్కు తినేవాడికి అరవై నాలుగు కూరలు", meaning: "ఇంటింటా అడుక్కునేవాడికి రకరకాలు దొరుకుతాయి, సొంతంగా వండుకునేవాడికి ఒక్కటే.", en: "One curry for the man who cooks, sixty-four for the man who begs." },
  { text: "వచ్చీరాని మాటలు, ఊరీఊరని ఊరగాయ రుచి", meaning: "పసిపిల్లల ముద్దుమాటలు, కొత్త ఊరగాయ భలే రుచి.", en: "A toddler's half-formed words and half-pickled pickle are the tastiest." },
  { text: "వస్తే కొండ, పోతే వెంట్రుక", meaning: "ప్రయత్నిస్తే లాభం పెద్దది, నష్టం చిన్నది.", en: "Win and it's a mountain, lose and it's a hair." },
  { text: "వడ్డించేవాడు మనవాడైతే కడబంతిలో కూర్చున్నా ఒకటే", meaning: "అధికారంలో మనవాడుంటే మనకు అన్యాయం జరగదు.", en: "If the server is your man, sitting at the end of the row makes no difference." },
  { text: "వసుదేవుడంతటివాడు గాడిద కాళ్ళు పట్టుకున్నట్లు", meaning: "గొప్పవాళ్ళు కూడా అవసరానికి తలవంచాల్సి రావడం.", en: "Even the great Vasudeva had to clasp a donkey's feet." },
  { text: "వాన రాకడ, ప్రాణం పోకడ ఎవరికీ తెలియదు", meaning: "వర్షం ఎప్పుడొస్తుందో, ప్రాణం ఎప్పుడు పోతుందో ఎవరూ చెప్పలేరు.", en: "No one knows when rain will come or life will go." },
  { text: "వాపును చూసి బలుపు అనుకున్నట్లు", meaning: "వాపును బలమనుకుని భ్రమపడటం.", en: "Mistaking swelling for strength." },
  { text: "వేపకాయంత వెర్రి", meaning: "కొంచెం పిచ్చితనం.", en: "A neem-seed's worth of madness." },
  { text: "వేన్నీళ్ళకు చన్నీళ్ళు తోడు", meaning: "చిన్న సాయమైనా పెద్ద పనికి ఉపయోగపడుతుంది.", en: "Cold water helps the hot — every bit of help counts." },
  { text: "వియ్యానికైనా కయ్యానికైనా సమ ఉజ్జీ ఉండాలి", meaning: "బంధుత్వానికైనా గొడవకైనా సమానస్థాయి ఉండాలి.", en: "For marriage or for a fight, match with an equal." },
  { text: "విగ్రహపుష్టి నైవేద్యనష్టి", meaning: "ఆకారం పెద్దదే కానీ ఉపయోగం లేదు; తిండి మాత్రం ఎక్కువ.", en: "A big idol eats up all the offerings — big body, little use." },
  { text: "వినాశకాలే విపరీత బుద్ధి", meaning: "చెడ్డకాలం వచ్చినప్పుడు బుద్ధి వక్రమార్గం పడుతుంది.", en: "When ruin approaches, the mind goes astray." },
  { text: "వెన్న తిన్నవాడు వెళ్ళిపోతే చల్ల తాగినవాణ్ణి చావమోదినట్టు", meaning: "అసలు దోషి తప్పించుకుంటే చిన్నవాడికి శిక్ష.", en: "The butter-thief escaped, so they thrashed the one who drank buttermilk." },

  // శ, ష, స, హ, క్ష
  { text: "శంఖంలో పోస్తేగానీ తీర్థం కాదు", meaning: "సరైన వ్యక్తి చెప్పినప్పుడే మాటకు విలువ.", en: "Water becomes holy only when poured from a conch." },
  { text: "శ్రుతి ముదిరి రాగాన పడింది", meaning: "చిన్న విషయం పెరిగి పెద్దదైపోవడం.", en: "The drone grew louder until it became a full melody." },
  { text: "శతకోటి దరిద్రాలకు అనంతకోటి ఉపాయాలు", meaning: "ఎన్ని కష్టాలున్నా వాటికి ఉపాయాలూ ఉంటాయి.", en: "For a hundred crore troubles, endless remedies." },
  { text: "శతకోటి లింగాలలో బోడిలింగం", meaning: "చాలామందిలో ఒకడు; ప్రత్యేకత లేనివాడు.", en: "One plain lingam among a hundred crore — nothing special." },
  { text: "శివుని ఆజ్ఞ లేనిదే చీమైనా కుట్టదు", meaning: "దైవ సంకల్పం లేనిదే ఏదీ జరగదు.", en: "Not even an ant bites without Shiva's will." },
  { text: "శ్వాస ఉన్నంతవరకే ఆశ", meaning: "బతికి ఉన్నంతవరకూ ఆశ ఉంటుంది.", en: "As long as there's breath, there's hope." },
  { text: "శొంఠి లేని కషాయం లేదు", meaning: "ప్రతి విషయంలో తలదూర్చేవాడు.", en: "No herbal brew without dry ginger — someone who's in everything." },
  { text: "సంతోషమే సగం బలం", meaning: "సంతోషంగా ఉండటమే సగం బలం.", en: "Happiness is half of one's strength." },
  { text: "సత్రం భోజనం, మఠం నిద్ర", meaning: "సొంత ఇల్లు లేకుండా ఇతరుల ఆశ్రయంలో బతకడం.", en: "Meals at the choultry, sleep at the monastery." },
  { text: "సముద్రమైనా ఈదవచ్చుగానీ సంసారం ఈదడం కష్టం", meaning: "కుటుంబ బాధ్యతలు మోయడం చాలా కష్టం.", en: "You can swim the ocean, but not the sea of family life." },
  { text: "సర్వేంద్రియాణాం నయనం ప్రధానం", meaning: "అన్ని ఇంద్రియాల్లో కన్ను ముఖ్యమైనది.", en: "Of all senses, the eye is foremost." },
  { text: "సీత కష్టాలు సీతవి, పీత కష్టాలు పీతవి", meaning: "ఎవరి కష్టాలు వారికి పెద్దవే.", en: "Sita has her troubles, the crab has its own." },
  { text: "సూది కోసం సోదికి వెళితే పాత రంకంతా బయటపడిందట", meaning: "చిన్న విషయం కోసం వెతికితే పాత రహస్యాలన్నీ బయటపడటం.", en: "Consulted a soothsayer about a lost needle, and old scandals came out." },
  { text: "సొమ్మొకడిది, సోకొకడిది", meaning: "సొమ్ము ఒకరిదైతే సుఖం, పేరు మరొకరికి.", en: "One man's money, another man's show." },
  { text: "సామెత లేని మాట, ఆమెత లేని ఇల్లు", meaning: "సామెత లేని మాట విందు లేని ఇల్లులా చప్పగా ఉంటుంది.", en: "Speech without a proverb is like a house without a feast." },
  { text: "సన్నాయి నొక్కులే గానీ సంగీతం లేదు", meaning: "హంగులే తప్ప అసలు విషయం లేదు.", en: "All the flourishes of the pipe, but no music." },
  { text: "సింగడు అద్దంకి వెళ్ళినట్టు", meaning: "ఊరెళ్ళి ఏ పనీ చేయకుండా తిరిగిరావడం.", en: "Like Singadu's trip to Addanki — went and came back with nothing done." },
  { text: "హనుమంతుడి ముందా కుప్పిగంతులు", meaning: "నిపుణుడి ముందు తన ప్రతిభ ప్రదర్శించబోవడం.", en: "Somersaults in front of Hanuman?" },
  { text: "హరిశ్చంద్రుడి నోట అబద్ధం రాదు, నా నోట నిజం రాదు", meaning: "ఎప్పుడూ అబద్ధాలే చెప్పేవాడిని ఎగతాళి చేసే సామెత.", en: "No lie from Harishchandra's mouth, and no truth from mine." },
  { text: "హాస్యగాడిని తేలు కుట్టినట్లు", meaning: "ఎప్పుడూ హాస్యమాడేవాడు నిజంగా బాధపడినా ఎవరూ నమ్మరు.", en: "The joker stung by a scorpion — no one believes his cries." },
  { text: "క్షణం తీరిక లేదు, దమ్మిడీ ఆదాయం లేదు", meaning: "తెగ హడావుడి, కానీ ఒరిగేదేమీ లేదు.", en: "Not a moment's rest, not a penny earned." },
  { text: "క్షేత్రమెరిగి విత్తనం, పాత్రమెరిగి దానం", meaning: "నేలను చూసి విత్తాలి, అర్హతను చూసి దానం చేయాలి.", en: "Know the field before sowing, the person before giving." },
];
